// src/app.ts
import { toNodeHandler } from "better-auth/node";
import express from "express";

// src/lib/auth.ts
import { betterAuth } from "better-auth";
import { prismaAdapter } from "better-auth/adapters/prisma";

// src/lib/prisma.ts
import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";

// generated/prisma/client.ts
import * as path from "path";
import { fileURLToPath } from "url";

// generated/prisma/internal/class.ts
import * as runtime from "@prisma/client/runtime/client";
var config = {
  "previewFeatures": [],
  "clientVersion": "7.4.0",
  "engineVersion": "ab56fe763f921d033a6c195e7ddeb3e255bdbb57",
  "activeProvider": "postgresql",
  "inlineSchema": 'generator client {\n  provider = "prisma-client"\n  output   = "../generated/prisma"\n}\n\ndatasource db {\n  provider = "postgresql"\n}\n\nenum Role {\n  ADMIN\n  SELLER\n  CUSTOMER\n}\n\nenum OrderStatus {\n  PENDING\n  PROCESSING\n  SHIPPED\n  CANCELLED\n  DELIVERED\n}\n\nenum UserStatus {\n  ACTIVE\n  BLOCKED\n}\n\nmodel Medicines {\n  id           String  @id @default(uuid())\n  name         String\n  description  String\n  price        Float\n  stock        Int\n  image        String?\n  manufacturer String\n\n  Category_id String\n  Category    Categories @relation(fields: [Category_id], references: [id], onDelete: Cascade)\n\n  Seller_id String\n  Seller    User   @relation(fields: [Seller_id], references: [id], onDelete: Cascade)\n\n  createdAt DateTime  @default(now())\n  updatedAt DateTime  @updatedAt\n  reviews   Reviews[]\n  orders    Orders[]\n  carts     Cart[]\n}\n\nmodel Cart {\n  id        String   @id @default(uuid())\n  quantity  Int      @default(1)\n  createdAt DateTime @default(now())\n\n  Customer_id String\n  Customer    User   @relation(fields: [Customer_id], references: [id])\n\n  Medicine_id String\n  Medicine    Medicines @relation(fields: [Medicine_id], references: [id])\n\n  @@unique([Customer_id, Medicine_id])\n}\n\nmodel Orders {\n  id              String      @id @default(uuid())\n  status          OrderStatus @default(PENDING) // * enum\n  paymentMethod   String\n  TotalPrice      Float\n  quantity        Int\n  shippingAddress String\n  createdAt       DateTime    @default(now())\n  updatedAt       DateTime    @updatedAt\n\n  Seller_id String\n  Seller    User   @relation("SellerOrders", fields: [Seller_id], references: [id])\n\n  Medicine_id String\n  Medicine    Medicines @relation(fields: [Medicine_id], references: [id])\n\n  Customer_id String\n  Customer    User   @relation("CustomerOrders", fields: [Customer_id], references: [id], onDelete: Cascade)\n}\n\nmodel Categories {\n  id          String   @id @default(uuid())\n  name        String   @unique\n  description String?\n  createdAt   DateTime @default(now())\n\n  medicines Medicines[]\n}\n\nmodel Reviews {\n  id        String   @id @default(uuid())\n  rating    Int\n  commnet   String\n  createdAt DateTime @default(now())\n\n  medicine_id String\n  Medicine    Medicines @relation(fields: [medicine_id], references: [id], onDelete: Cascade)\n\n  customer_id String\n  Customer    User   @relation(fields: [customer_id], references: [id])\n}\n\nmodel User {\n  id            String     @id @default(uuid())\n  name          String\n  email         String     @unique\n  emailVerified Boolean    @default(false)\n  role          Role       @default(CUSTOMER)\n  status        UserStatus @default(ACTIVE)\n  image         String?\n  createdAt     DateTime   @default(now())\n  updatedAt     DateTime   @updatedAt\n  sessions      Session[]\n  accounts      Account[]\n\n  medicines Medicines[]\n\n  reviews        Reviews[]\n  CustomerOrders Orders[]  @relation("CustomerOrders")\n  SellerOrders   Orders[]  @relation("SellerOrders")\n  carts          Cart[]\n\n  @@map("user")\n}\n\nmodel Session {\n  id        String   @id\n  expiresAt DateTime\n  token     String\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n  ipAddress String?\n  userAgent String?\n  userId    String\n  user      User     @relation(fields: [userId], references: [id], onDelete: Cascade)\n\n  @@unique([token])\n  @@index([userId])\n  @@map("session")\n}\n\nmodel Account {\n  id                    String    @id\n  accountId             String\n  providerId            String\n  userId                String\n  user                  User      @relation(fields: [userId], references: [id], onDelete: Cascade)\n  accessToken           String?\n  refreshToken          String?\n  idToken               String?\n  accessTokenExpiresAt  DateTime?\n  refreshTokenExpiresAt DateTime?\n  scope                 String?\n  password              String?\n  createdAt             DateTime  @default(now())\n  updatedAt             DateTime  @updatedAt\n\n  @@index([userId])\n  @@map("account")\n}\n\nmodel Verification {\n  id         String   @id\n  identifier String\n  value      String\n  expiresAt  DateTime\n  createdAt  DateTime @default(now())\n  updatedAt  DateTime @updatedAt\n\n  @@index([identifier])\n  @@map("verification")\n}\n',
  "runtimeDataModel": {
    "models": {},
    "enums": {},
    "types": {}
  },
  "parameterizationSchema": {
    "strings": [],
    "graph": ""
  }
};
config.runtimeDataModel = JSON.parse('{"models":{"Medicines":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"description","kind":"scalar","type":"String"},{"name":"price","kind":"scalar","type":"Float"},{"name":"stock","kind":"scalar","type":"Int"},{"name":"image","kind":"scalar","type":"String"},{"name":"manufacturer","kind":"scalar","type":"String"},{"name":"Category_id","kind":"scalar","type":"String"},{"name":"Category","kind":"object","type":"Categories","relationName":"CategoriesToMedicines"},{"name":"Seller_id","kind":"scalar","type":"String"},{"name":"Seller","kind":"object","type":"User","relationName":"MedicinesToUser"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"reviews","kind":"object","type":"Reviews","relationName":"MedicinesToReviews"},{"name":"orders","kind":"object","type":"Orders","relationName":"MedicinesToOrders"},{"name":"carts","kind":"object","type":"Cart","relationName":"CartToMedicines"}],"dbName":null},"Cart":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"quantity","kind":"scalar","type":"Int"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"Customer_id","kind":"scalar","type":"String"},{"name":"Customer","kind":"object","type":"User","relationName":"CartToUser"},{"name":"Medicine_id","kind":"scalar","type":"String"},{"name":"Medicine","kind":"object","type":"Medicines","relationName":"CartToMedicines"}],"dbName":null},"Orders":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"status","kind":"enum","type":"OrderStatus"},{"name":"paymentMethod","kind":"scalar","type":"String"},{"name":"TotalPrice","kind":"scalar","type":"Float"},{"name":"quantity","kind":"scalar","type":"Int"},{"name":"shippingAddress","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"Seller_id","kind":"scalar","type":"String"},{"name":"Seller","kind":"object","type":"User","relationName":"SellerOrders"},{"name":"Medicine_id","kind":"scalar","type":"String"},{"name":"Medicine","kind":"object","type":"Medicines","relationName":"MedicinesToOrders"},{"name":"Customer_id","kind":"scalar","type":"String"},{"name":"Customer","kind":"object","type":"User","relationName":"CustomerOrders"}],"dbName":null},"Categories":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"description","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"medicines","kind":"object","type":"Medicines","relationName":"CategoriesToMedicines"}],"dbName":null},"Reviews":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"rating","kind":"scalar","type":"Int"},{"name":"commnet","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"medicine_id","kind":"scalar","type":"String"},{"name":"Medicine","kind":"object","type":"Medicines","relationName":"MedicinesToReviews"},{"name":"customer_id","kind":"scalar","type":"String"},{"name":"Customer","kind":"object","type":"User","relationName":"ReviewsToUser"}],"dbName":null},"User":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"email","kind":"scalar","type":"String"},{"name":"emailVerified","kind":"scalar","type":"Boolean"},{"name":"role","kind":"enum","type":"Role"},{"name":"status","kind":"enum","type":"UserStatus"},{"name":"image","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"sessions","kind":"object","type":"Session","relationName":"SessionToUser"},{"name":"accounts","kind":"object","type":"Account","relationName":"AccountToUser"},{"name":"medicines","kind":"object","type":"Medicines","relationName":"MedicinesToUser"},{"name":"reviews","kind":"object","type":"Reviews","relationName":"ReviewsToUser"},{"name":"CustomerOrders","kind":"object","type":"Orders","relationName":"CustomerOrders"},{"name":"SellerOrders","kind":"object","type":"Orders","relationName":"SellerOrders"},{"name":"carts","kind":"object","type":"Cart","relationName":"CartToUser"}],"dbName":"user"},"Session":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"expiresAt","kind":"scalar","type":"DateTime"},{"name":"token","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"ipAddress","kind":"scalar","type":"String"},{"name":"userAgent","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"user","kind":"object","type":"User","relationName":"SessionToUser"}],"dbName":"session"},"Account":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"accountId","kind":"scalar","type":"String"},{"name":"providerId","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"user","kind":"object","type":"User","relationName":"AccountToUser"},{"name":"accessToken","kind":"scalar","type":"String"},{"name":"refreshToken","kind":"scalar","type":"String"},{"name":"idToken","kind":"scalar","type":"String"},{"name":"accessTokenExpiresAt","kind":"scalar","type":"DateTime"},{"name":"refreshTokenExpiresAt","kind":"scalar","type":"DateTime"},{"name":"scope","kind":"scalar","type":"String"},{"name":"password","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":"account"},"Verification":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"identifier","kind":"scalar","type":"String"},{"name":"value","kind":"scalar","type":"String"},{"name":"expiresAt","kind":"scalar","type":"DateTime"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":"verification"}},"enums":{},"types":{}}');
config.parameterizationSchema = {
  strings: JSON.parse('["where","orderBy","cursor","medicines","_count","Category","user","sessions","accounts","Medicine","Customer","reviews","Seller","CustomerOrders","SellerOrders","carts","orders","Medicines.findUnique","Medicines.findUniqueOrThrow","Medicines.findFirst","Medicines.findFirstOrThrow","Medicines.findMany","data","Medicines.createOne","Medicines.createMany","Medicines.createManyAndReturn","Medicines.updateOne","Medicines.updateMany","Medicines.updateManyAndReturn","create","update","Medicines.upsertOne","Medicines.deleteOne","Medicines.deleteMany","having","_avg","_sum","_min","_max","Medicines.groupBy","Medicines.aggregate","Cart.findUnique","Cart.findUniqueOrThrow","Cart.findFirst","Cart.findFirstOrThrow","Cart.findMany","Cart.createOne","Cart.createMany","Cart.createManyAndReturn","Cart.updateOne","Cart.updateMany","Cart.updateManyAndReturn","Cart.upsertOne","Cart.deleteOne","Cart.deleteMany","Cart.groupBy","Cart.aggregate","Orders.findUnique","Orders.findUniqueOrThrow","Orders.findFirst","Orders.findFirstOrThrow","Orders.findMany","Orders.createOne","Orders.createMany","Orders.createManyAndReturn","Orders.updateOne","Orders.updateMany","Orders.updateManyAndReturn","Orders.upsertOne","Orders.deleteOne","Orders.deleteMany","Orders.groupBy","Orders.aggregate","Categories.findUnique","Categories.findUniqueOrThrow","Categories.findFirst","Categories.findFirstOrThrow","Categories.findMany","Categories.createOne","Categories.createMany","Categories.createManyAndReturn","Categories.updateOne","Categories.updateMany","Categories.updateManyAndReturn","Categories.upsertOne","Categories.deleteOne","Categories.deleteMany","Categories.groupBy","Categories.aggregate","Reviews.findUnique","Reviews.findUniqueOrThrow","Reviews.findFirst","Reviews.findFirstOrThrow","Reviews.findMany","Reviews.createOne","Reviews.createMany","Reviews.createManyAndReturn","Reviews.updateOne","Reviews.updateMany","Reviews.updateManyAndReturn","Reviews.upsertOne","Reviews.deleteOne","Reviews.deleteMany","Reviews.groupBy","Reviews.aggregate","User.findUnique","User.findUniqueOrThrow","User.findFirst","User.findFirstOrThrow","User.findMany","User.createOne","User.createMany","User.createManyAndReturn","User.updateOne","User.updateMany","User.updateManyAndReturn","User.upsertOne","User.deleteOne","User.deleteMany","User.groupBy","User.aggregate","Session.findUnique","Session.findUniqueOrThrow","Session.findFirst","Session.findFirstOrThrow","Session.findMany","Session.createOne","Session.createMany","Session.createManyAndReturn","Session.updateOne","Session.updateMany","Session.updateManyAndReturn","Session.upsertOne","Session.deleteOne","Session.deleteMany","Session.groupBy","Session.aggregate","Account.findUnique","Account.findUniqueOrThrow","Account.findFirst","Account.findFirstOrThrow","Account.findMany","Account.createOne","Account.createMany","Account.createManyAndReturn","Account.updateOne","Account.updateMany","Account.updateManyAndReturn","Account.upsertOne","Account.deleteOne","Account.deleteMany","Account.groupBy","Account.aggregate","Verification.findUnique","Verification.findUniqueOrThrow","Verification.findFirst","Verification.findFirstOrThrow","Verification.findMany","Verification.createOne","Verification.createMany","Verification.createManyAndReturn","Verification.updateOne","Verification.updateMany","Verification.updateManyAndReturn","Verification.upsertOne","Verification.deleteOne","Verification.deleteMany","Verification.groupBy","Verification.aggregate","AND","OR","NOT","id","identifier","value","expiresAt","createdAt","updatedAt","equals","in","notIn","lt","lte","gt","gte","not","contains","startsWith","endsWith","accountId","providerId","userId","accessToken","refreshToken","idToken","accessTokenExpiresAt","refreshTokenExpiresAt","scope","password","token","ipAddress","userAgent","name","email","emailVerified","Role","role","UserStatus","status","image","every","some","none","rating","commnet","medicine_id","customer_id","description","OrderStatus","paymentMethod","TotalPrice","quantity","shippingAddress","Seller_id","Medicine_id","Customer_id","price","stock","manufacturer","Category_id","Customer_id_Medicine_id","is","isNot","connectOrCreate","upsert","createMany","set","disconnect","delete","connect","updateMany","deleteMany","increment","decrement","multiply","divide"]'),
  graph: "1gRUkAETBQAAvAIAIAsAAJ4CACAMAACyAgAgDwAAoAIAIBAAAJ8CACCpAQAAuwIAMKoBAAADABCrAQAAuwIAMKwBAQAAAAGwAUAAggIAIbEBQACCAgAhygEBAIECACHRAQEAmgIAIdkBAQCBAgAh3wEBAIECACHiAQgAtgIAIeMBAgCxAgAh5AEBAIECACHlAQEAgQIAIQEAAAABACATBQAAvAIAIAsAAJ4CACAMAACyAgAgDwAAoAIAIBAAAJ8CACCpAQAAuwIAMKoBAAADABCrAQAAuwIAMKwBAQCBAgAhsAFAAIICACGxAUAAggIAIcoBAQCBAgAh0QEBAJoCACHZAQEAgQIAId8BAQCBAgAh4gEIALYCACHjAQIAsQIAIeQBAQCBAgAh5QEBAIECACEGBQAAlAQAIAsAAOsDACAMAACSBAAgDwAA7QMAIBAAAOwDACDRAQAAwgIAIAMAAAADACABAAAEADACAAABACABAAAAAwAgDAYAALICACCpAQAAugIAMKoBAAAHABCrAQAAugIAMKwBAQCBAgAhrwFAAIICACGwAUAAggIAIbEBQACCAgAhvwEBAIECACHHAQEAgQIAIcgBAQCaAgAhyQEBAJoCACEDBgAAkgQAIMgBAADCAgAgyQEAAMICACAMBgAAsgIAIKkBAAC6AgAwqgEAAAcAEKsBAAC6AgAwrAEBAAAAAa8BQACCAgAhsAFAAIICACGxAUAAggIAIb8BAQCBAgAhxwEBAAAAAcgBAQCaAgAhyQEBAJoCACEDAAAABwAgAQAACAAwAgAACQAgEQYAALICACCpAQAAuAIAMKoBAAALABCrAQAAuAIAMKwBAQCBAgAhsAFAAIICACGxAUAAggIAIb0BAQCBAgAhvgEBAIECACG_AQEAgQIAIcABAQCaAgAhwQEBAJoCACHCAQEAmgIAIcMBQAC5AgAhxAFAALkCACHFAQEAmgIAIcYBAQCaAgAhCAYAAJIEACDAAQAAwgIAIMEBAADCAgAgwgEAAMICACDDAQAAwgIAIMQBAADCAgAgxQEAAMICACDGAQAAwgIAIBEGAACyAgAgqQEAALgCADCqAQAACwAQqwEAALgCADCsAQEAAAABsAFAAIICACGxAUAAggIAIb0BAQCBAgAhvgEBAIECACG_AQEAgQIAIcABAQCaAgAhwQEBAJoCACHCAQEAmgIAIcMBQAC5AgAhxAFAALkCACHFAQEAmgIAIcYBAQCaAgAhAwAAAAsAIAEAAAwAMAIAAA0AIAMAAAADACABAAAEADACAAABACALCQAAswIAIAoAALICACCpAQAAtwIAMKoBAAAQABCrAQAAtwIAMKwBAQCBAgAhsAFAAIICACHVAQIAsQIAIdYBAQCBAgAh1wEBAIECACHYAQEAgQIAIQIJAACTBAAgCgAAkgQAIAsJAACzAgAgCgAAsgIAIKkBAAC3AgAwqgEAABAAEKsBAAC3AgAwrAEBAAAAAbABQACCAgAh1QECALECACHWAQEAgQIAIdcBAQCBAgAh2AEBAIECACEDAAAAEAAgAQAAEQAwAgAAEgAgEQkAALMCACAKAACyAgAgDAAAsgIAIKkBAAC0AgAwqgEAABQAEKsBAAC0AgAwrAEBAIECACGwAUAAggIAIbEBQACCAgAh0AEAALUC2wEi2wEBAIECACHcAQgAtgIAId0BAgCxAgAh3gEBAIECACHfAQEAgQIAIeABAQCBAgAh4QEBAIECACEDCQAAkwQAIAoAAJIEACAMAACSBAAgEQkAALMCACAKAACyAgAgDAAAsgIAIKkBAAC0AgAwqgEAABQAEKsBAAC0AgAwrAEBAAAAAbABQACCAgAhsQFAAIICACHQAQAAtQLbASLbAQEAgQIAIdwBCAC2AgAh3QECALECACHeAQEAgQIAId8BAQCBAgAh4AEBAIECACHhAQEAgQIAIQMAAAAUACABAAAVADACAAAWACADAAAAFAAgAQAAFQAwAgAAFgAgCgkAALMCACAKAACyAgAgqQEAALACADCqAQAAGQAQqwEAALACADCsAQEAgQIAIbABQACCAgAh3QECALECACHgAQEAgQIAIeEBAQCBAgAhAgkAAJMEACAKAACSBAAgCwkAALMCACAKAACyAgAgqQEAALACADCqAQAAGQAQqwEAALACADCsAQEAAAABsAFAAIICACHdAQIAsQIAIeABAQCBAgAh4QEBAIECACHmAQAArwIAIAMAAAAZACABAAAaADACAAAbACABAAAABwAgAQAAAAsAIAEAAAADACABAAAAEAAgAQAAABQAIAEAAAAUACABAAAAGQAgAwAAABAAIAEAABEAMAIAABIAIAMAAAAUACABAAAVADACAAAWACADAAAAGQAgAQAAGgAwAgAAGwAgAQAAABAAIAEAAAAUACABAAAAGQAgAQAAAAEAIAMAAAADACABAAAEADACAAABACADAAAAAwAgAQAABAAwAgAAAQAgAwAAAAMAIAEAAAQAMAIAAAEAIBAFAADFAwAgCwAAxgMAIAwAAIEEACAPAADIAwAgEAAAxwMAIKwBAQAAAAGwAUAAAAABsQFAAAAAAcoBAQAAAAHRAQEAAAAB2QEBAAAAAd8BAQAAAAHiAQgAAAAB4wECAAAAAeQBAQAAAAHlAQEAAAABARYAAC4AIAusAQEAAAABsAFAAAAAAbEBQAAAAAHKAQEAAAAB0QEBAAAAAdkBAQAAAAHfAQEAAAAB4gEIAAAAAeMBAgAAAAHkAQEAAAAB5QEBAAAAAQEWAAAwADABFgAAMAAwEAUAAKEDACALAACiAwAgDAAA_wMAIA8AAKQDACAQAACjAwAgrAEBAMACACGwAUAAwQIAIbEBQADBAgAhygEBAMACACHRAQEAxgIAIdkBAQDAAgAh3wEBAMACACHiAQgA9gIAIeMBAgDmAgAh5AEBAMACACHlAQEAwAIAIQIAAAABACAWAAAzACALrAEBAMACACGwAUAAwQIAIbEBQADBAgAhygEBAMACACHRAQEAxgIAIdkBAQDAAgAh3wEBAMACACHiAQgA9gIAIeMBAgDmAgAh5AEBAMACACHlAQEAwAIAIQIAAAADACAWAAA1ACACAAAAAwAgFgAANQAgAwAAAAEAIB0AAC4AIB4AADMAIAEAAAABACABAAAAAwAgBgQAAI0EACAjAACOBAAgJAAAkQQAICUAAJAEACAmAACPBAAg0QEAAMICACAOqQEAAK4CADCqAQAAPAAQqwEAAK4CADCsAQEA-QEAIbABQAD6AQAhsQFAAPoBACHKAQEA-QEAIdEBAQCEAgAh2QEBAPkBACHfAQEA-QEAIeIBCACpAgAh4wECAKICACHkAQEA-QEAIeUBAQD5AQAhAwAAAAMAIAEAADsAMCIAADwAIAMAAAADACABAAAEADACAAABACABAAAAGwAgAQAAABsAIAMAAAAZACABAAAaADACAAAbACADAAAAGQAgAQAAGgAwAgAAGwAgAwAAABkAIAEAABoAMAIAABsAIAcJAADqAgAgCgAArwMAIKwBAQAAAAGwAUAAAAAB3QECAAAAAeABAQAAAAHhAQEAAAABARYAAEQAIAWsAQEAAAABsAFAAAAAAd0BAgAAAAHgAQEAAAAB4QEBAAAAAQEWAABGADABFgAARgAwBwkAAOgCACAKAACtAwAgrAEBAMACACGwAUAAwQIAId0BAgDmAgAh4AEBAMACACHhAQEAwAIAIQIAAAAbACAWAABJACAFrAEBAMACACGwAUAAwQIAId0BAgDmAgAh4AEBAMACACHhAQEAwAIAIQIAAAAZACAWAABLACACAAAAGQAgFgAASwAgAwAAABsAIB0AAEQAIB4AAEkAIAEAAAAbACABAAAAGQAgBQQAAIgEACAjAACJBAAgJAAAjAQAICUAAIsEACAmAACKBAAgCKkBAACtAgAwqgEAAFIAEKsBAACtAgAwrAEBAPkBACGwAUAA-gEAId0BAgCiAgAh4AEBAPkBACHhAQEA-QEAIQMAAAAZACABAABRADAiAABSACADAAAAGQAgAQAAGgAwAgAAGwAgAQAAABYAIAEAAAAWACADAAAAFAAgAQAAFQAwAgAAFgAgAwAAABQAIAEAABUAMAIAABYAIAMAAAAUACABAAAVADACAAAWACAOCQAA-wIAIAoAAPwCACAMAACHAwAgrAEBAAAAAbABQAAAAAGxAUAAAAAB0AEAAADbAQLbAQEAAAAB3AEIAAAAAd0BAgAAAAHeAQEAAAAB3wEBAAAAAeABAQAAAAHhAQEAAAABARYAAFoAIAusAQEAAAABsAFAAAAAAbEBQAAAAAHQAQAAANsBAtsBAQAAAAHcAQgAAAAB3QECAAAAAd4BAQAAAAHfAQEAAAAB4AEBAAAAAeEBAQAAAAEBFgAAXAAwARYAAFwAMA4JAAD4AgAgCgAA-QIAIAwAAIUDACCsAQEAwAIAIbABQADBAgAhsQFAAMECACHQAQAA9QLbASLbAQEAwAIAIdwBCAD2AgAh3QECAOYCACHeAQEAwAIAId8BAQDAAgAh4AEBAMACACHhAQEAwAIAIQIAAAAWACAWAABfACALrAEBAMACACGwAUAAwQIAIbEBQADBAgAh0AEAAPUC2wEi2wEBAMACACHcAQgA9gIAId0BAgDmAgAh3gEBAMACACHfAQEAwAIAIeABAQDAAgAh4QEBAMACACECAAAAFAAgFgAAYQAgAgAAABQAIBYAAGEAIAMAAAAWACAdAABaACAeAABfACABAAAAFgAgAQAAABQAIAUEAACDBAAgIwAAhAQAICQAAIcEACAlAACGBAAgJgAAhQQAIA6pAQAApwIAMKoBAABoABCrAQAApwIAMKwBAQD5AQAhsAFAAPoBACGxAUAA-gEAIdABAACoAtsBItsBAQD5AQAh3AEIAKkCACHdAQIAogIAId4BAQD5AQAh3wEBAPkBACHgAQEA-QEAIeEBAQD5AQAhAwAAABQAIAEAAGcAMCIAAGgAIAMAAAAUACABAAAVADACAAAWACAIAwAAnQIAIKkBAACmAgAwqgEAAG4AEKsBAACmAgAwrAEBAAAAAbABQACCAgAhygEBAAAAAdkBAQCaAgAhAQAAAGsAIAEAAABrACAIAwAAnQIAIKkBAACmAgAwqgEAAG4AEKsBAACmAgAwrAEBAIECACGwAUAAggIAIcoBAQCBAgAh2QEBAJoCACECAwAA6gMAINkBAADCAgAgAwAAAG4AIAEAAG8AMAIAAGsAIAMAAABuACABAABvADACAABrACADAAAAbgAgAQAAbwAwAgAAawAgBQMAAIIEACCsAQEAAAABsAFAAAAAAcoBAQAAAAHZAQEAAAABARYAAHMAIASsAQEAAAABsAFAAAAAAcoBAQAAAAHZAQEAAAABARYAAHUAMAEWAAB1ADAFAwAA9gMAIKwBAQDAAgAhsAFAAMECACHKAQEAwAIAIdkBAQDGAgAhAgAAAGsAIBYAAHgAIASsAQEAwAIAIbABQADBAgAhygEBAMACACHZAQEAxgIAIQIAAABuACAWAAB6ACACAAAAbgAgFgAAegAgAwAAAGsAIB0AAHMAIB4AAHgAIAEAAABrACABAAAAbgAgBAQAAPMDACAlAAD1AwAgJgAA9AMAINkBAADCAgAgB6kBAAClAgAwqgEAAIEBABCrAQAApQIAMKwBAQD5AQAhsAFAAPoBACHKAQEA-QEAIdkBAQCEAgAhAwAAAG4AIAEAAIABADAiAACBAQAgAwAAAG4AIAEAAG8AMAIAAGsAIAEAAAASACABAAAAEgAgAwAAABAAIAEAABEAMAIAABIAIAMAAAAQACABAAARADACAAASACADAAAAEAAgAQAAEQAwAgAAEgAgCAkAAJUDACAKAADDAwAgrAEBAAAAAbABQAAAAAHVAQIAAAAB1gEBAAAAAdcBAQAAAAHYAQEAAAABARYAAIkBACAGrAEBAAAAAbABQAAAAAHVAQIAAAAB1gEBAAAAAdcBAQAAAAHYAQEAAAABARYAAIsBADABFgAAiwEAMAgJAACTAwAgCgAAwQMAIKwBAQDAAgAhsAFAAMECACHVAQIA5gIAIdYBAQDAAgAh1wEBAMACACHYAQEAwAIAIQIAAAASACAWAACOAQAgBqwBAQDAAgAhsAFAAMECACHVAQIA5gIAIdYBAQDAAgAh1wEBAMACACHYAQEAwAIAIQIAAAAQACAWAACQAQAgAgAAABAAIBYAAJABACADAAAAEgAgHQAAiQEAIB4AAI4BACABAAAAEgAgAQAAABAAIAUEAADuAwAgIwAA7wMAICQAAPIDACAlAADxAwAgJgAA8AMAIAmpAQAAoQIAMKoBAACXAQAQqwEAAKECADCsAQEA-QEAIbABQAD6AQAh1QECAKICACHWAQEA-QEAIdcBAQD5AQAh2AEBAPkBACEDAAAAEAAgAQAAlgEAMCIAAJcBACADAAAAEAAgAQAAEQAwAgAAEgAgEwMAAJ0CACAHAACbAgAgCAAAnAIAIAsAAJ4CACANAACfAgAgDgAAnwIAIA8AAKACACCpAQAAlgIAMKoBAACdAQAQqwEAAJYCADCsAQEAAAABsAFAAIICACGxAUAAggIAIcoBAQCBAgAhywEBAAAAAcwBIACXAgAhzgEAAJgCzgEi0AEAAJkC0AEi0QEBAJoCACEBAAAAmgEAIAEAAACaAQAgEwMAAJ0CACAHAACbAgAgCAAAnAIAIAsAAJ4CACANAACfAgAgDgAAnwIAIA8AAKACACCpAQAAlgIAMKoBAACdAQAQqwEAAJYCADCsAQEAgQIAIbABQACCAgAhsQFAAIICACHKAQEAgQIAIcsBAQCBAgAhzAEgAJcCACHOAQAAmALOASLQAQAAmQLQASLRAQEAmgIAIQgDAADqAwAgBwAA6AMAIAgAAOkDACALAADrAwAgDQAA7AMAIA4AAOwDACAPAADtAwAg0QEAAMICACADAAAAnQEAIAEAAJ4BADACAACaAQAgAwAAAJ0BACABAACeAQAwAgAAmgEAIAMAAACdAQAgAQAAngEAMAIAAJoBACAQAwAA4wMAIAcAAOEDACAIAADiAwAgCwAA5AMAIA0AAOUDACAOAADmAwAgDwAA5wMAIKwBAQAAAAGwAUAAAAABsQFAAAAAAcoBAQAAAAHLAQEAAAABzAEgAAAAAc4BAAAAzgEC0AEAAADQAQLRAQEAAAABARYAAKIBACAJrAEBAAAAAbABQAAAAAGxAUAAAAABygEBAAAAAcsBAQAAAAHMASAAAAABzgEAAADOAQLQAQAAANABAtEBAQAAAAEBFgAApAEAMAEWAACkAQAwEAMAANcCACAHAADVAgAgCAAA1gIAIAsAANgCACANAADZAgAgDgAA2gIAIA8AANsCACCsAQEAwAIAIbABQADBAgAhsQFAAMECACHKAQEAwAIAIcsBAQDAAgAhzAEgANICACHOAQAA0wLOASLQAQAA1ALQASLRAQEAxgIAIQIAAACaAQAgFgAApwEAIAmsAQEAwAIAIbABQADBAgAhsQFAAMECACHKAQEAwAIAIcsBAQDAAgAhzAEgANICACHOAQAA0wLOASLQAQAA1ALQASLRAQEAxgIAIQIAAACdAQAgFgAAqQEAIAIAAACdAQAgFgAAqQEAIAMAAACaAQAgHQAAogEAIB4AAKcBACABAAAAmgEAIAEAAACdAQAgBAQAAM8CACAlAADRAgAgJgAA0AIAINEBAADCAgAgDKkBAACMAgAwqgEAALABABCrAQAAjAIAMKwBAQD5AQAhsAFAAPoBACGxAUAA-gEAIcoBAQD5AQAhywEBAPkBACHMASAAjQIAIc4BAACOAs4BItABAACPAtABItEBAQCEAgAhAwAAAJ0BACABAACvAQAwIgAAsAEAIAMAAACdAQAgAQAAngEAMAIAAJoBACABAAAACQAgAQAAAAkAIAMAAAAHACABAAAIADACAAAJACADAAAABwAgAQAACAAwAgAACQAgAwAAAAcAIAEAAAgAMAIAAAkAIAkGAADOAgAgrAEBAAAAAa8BQAAAAAGwAUAAAAABsQFAAAAAAb8BAQAAAAHHAQEAAAAByAEBAAAAAckBAQAAAAEBFgAAuAEAIAisAQEAAAABrwFAAAAAAbABQAAAAAGxAUAAAAABvwEBAAAAAccBAQAAAAHIAQEAAAAByQEBAAAAAQEWAAC6AQAwARYAALoBADAJBgAAzQIAIKwBAQDAAgAhrwFAAMECACGwAUAAwQIAIbEBQADBAgAhvwEBAMACACHHAQEAwAIAIcgBAQDGAgAhyQEBAMYCACECAAAACQAgFgAAvQEAIAisAQEAwAIAIa8BQADBAgAhsAFAAMECACGxAUAAwQIAIb8BAQDAAgAhxwEBAMACACHIAQEAxgIAIckBAQDGAgAhAgAAAAcAIBYAAL8BACACAAAABwAgFgAAvwEAIAMAAAAJACAdAAC4AQAgHgAAvQEAIAEAAAAJACABAAAABwAgBQQAAMoCACAlAADMAgAgJgAAywIAIMgBAADCAgAgyQEAAMICACALqQEAAIsCADCqAQAAxgEAEKsBAACLAgAwrAEBAPkBACGvAUAA-gEAIbABQAD6AQAhsQFAAPoBACG_AQEA-QEAIccBAQD5AQAhyAEBAIQCACHJAQEAhAIAIQMAAAAHACABAADFAQAwIgAAxgEAIAMAAAAHACABAAAIADACAAAJACABAAAADQAgAQAAAA0AIAMAAAALACABAAAMADACAAANACADAAAACwAgAQAADAAwAgAADQAgAwAAAAsAIAEAAAwAMAIAAA0AIA4GAADJAgAgrAEBAAAAAbABQAAAAAGxAUAAAAABvQEBAAAAAb4BAQAAAAG_AQEAAAABwAEBAAAAAcEBAQAAAAHCAQEAAAABwwFAAAAAAcQBQAAAAAHFAQEAAAABxgEBAAAAAQEWAADOAQAgDawBAQAAAAGwAUAAAAABsQFAAAAAAb0BAQAAAAG-AQEAAAABvwEBAAAAAcABAQAAAAHBAQEAAAABwgEBAAAAAcMBQAAAAAHEAUAAAAABxQEBAAAAAcYBAQAAAAEBFgAA0AEAMAEWAADQAQAwDgYAAMgCACCsAQEAwAIAIbABQADBAgAhsQFAAMECACG9AQEAwAIAIb4BAQDAAgAhvwEBAMACACHAAQEAxgIAIcEBAQDGAgAhwgEBAMYCACHDAUAAxwIAIcQBQADHAgAhxQEBAMYCACHGAQEAxgIAIQIAAAANACAWAADTAQAgDawBAQDAAgAhsAFAAMECACGxAUAAwQIAIb0BAQDAAgAhvgEBAMACACG_AQEAwAIAIcABAQDGAgAhwQEBAMYCACHCAQEAxgIAIcMBQADHAgAhxAFAAMcCACHFAQEAxgIAIcYBAQDGAgAhAgAAAAsAIBYAANUBACACAAAACwAgFgAA1QEAIAMAAAANACAdAADOAQAgHgAA0wEAIAEAAAANACABAAAACwAgCgQAAMMCACAlAADFAgAgJgAAxAIAIMABAADCAgAgwQEAAMICACDCAQAAwgIAIMMBAADCAgAgxAEAAMICACDFAQAAwgIAIMYBAADCAgAgEKkBAACDAgAwqgEAANwBABCrAQAAgwIAMKwBAQD5AQAhsAFAAPoBACGxAUAA-gEAIb0BAQD5AQAhvgEBAPkBACG_AQEA-QEAIcABAQCEAgAhwQEBAIQCACHCAQEAhAIAIcMBQACFAgAhxAFAAIUCACHFAQEAhAIAIcYBAQCEAgAhAwAAAAsAIAEAANsBADAiAADcAQAgAwAAAAsAIAEAAAwAMAIAAA0AIAmpAQAAgAIAMKoBAADiAQAQqwEAAIACADCsAQEAAAABrQEBAIECACGuAQEAgQIAIa8BQACCAgAhsAFAAIICACGxAUAAggIAIQEAAADfAQAgAQAAAN8BACAJqQEAAIACADCqAQAA4gEAEKsBAACAAgAwrAEBAIECACGtAQEAgQIAIa4BAQCBAgAhrwFAAIICACGwAUAAggIAIbEBQACCAgAhAAMAAADiAQAgAQAA4wEAMAIAAN8BACADAAAA4gEAIAEAAOMBADACAADfAQAgAwAAAOIBACABAADjAQAwAgAA3wEAIAasAQEAAAABrQEBAAAAAa4BAQAAAAGvAUAAAAABsAFAAAAAAbEBQAAAAAEBFgAA5wEAIAasAQEAAAABrQEBAAAAAa4BAQAAAAGvAUAAAAABsAFAAAAAAbEBQAAAAAEBFgAA6QEAMAEWAADpAQAwBqwBAQDAAgAhrQEBAMACACGuAQEAwAIAIa8BQADBAgAhsAFAAMECACGxAUAAwQIAIQIAAADfAQAgFgAA7AEAIAasAQEAwAIAIa0BAQDAAgAhrgEBAMACACGvAUAAwQIAIbABQADBAgAhsQFAAMECACECAAAA4gEAIBYAAO4BACACAAAA4gEAIBYAAO4BACADAAAA3wEAIB0AAOcBACAeAADsAQAgAQAAAN8BACABAAAA4gEAIAMEAAC9AgAgJQAAvwIAICYAAL4CACAJqQEAAPgBADCqAQAA9QEAEKsBAAD4AQAwrAEBAPkBACGtAQEA-QEAIa4BAQD5AQAhrwFAAPoBACGwAUAA-gEAIbEBQAD6AQAhAwAAAOIBACABAAD0AQAwIgAA9QEAIAMAAADiAQAgAQAA4wEAMAIAAN8BACAJqQEAAPgBADCqAQAA9QEAEKsBAAD4AQAwrAEBAPkBACGtAQEA-QEAIa4BAQD5AQAhrwFAAPoBACGwAUAA-gEAIbEBQAD6AQAhDgQAAPwBACAlAAD_AQAgJgAA_wEAILIBAQAAAAGzAQEAAAAEtAEBAAAABLUBAQAAAAG2AQEAAAABtwEBAAAAAbgBAQAAAAG5AQEA_gEAIboBAQAAAAG7AQEAAAABvAEBAAAAAQsEAAD8AQAgJQAA_QEAICYAAP0BACCyAUAAAAABswFAAAAABLQBQAAAAAS1AUAAAAABtgFAAAAAAbcBQAAAAAG4AUAAAAABuQFAAPsBACELBAAA_AEAICUAAP0BACAmAAD9AQAgsgFAAAAAAbMBQAAAAAS0AUAAAAAEtQFAAAAAAbYBQAAAAAG3AUAAAAABuAFAAAAAAbkBQAD7AQAhCLIBAgAAAAGzAQIAAAAEtAECAAAABLUBAgAAAAG2AQIAAAABtwECAAAAAbgBAgAAAAG5AQIA_AEAIQiyAUAAAAABswFAAAAABLQBQAAAAAS1AUAAAAABtgFAAAAAAbcBQAAAAAG4AUAAAAABuQFAAP0BACEOBAAA_AEAICUAAP8BACAmAAD_AQAgsgEBAAAAAbMBAQAAAAS0AQEAAAAEtQEBAAAAAbYBAQAAAAG3AQEAAAABuAEBAAAAAbkBAQD-AQAhugEBAAAAAbsBAQAAAAG8AQEAAAABC7IBAQAAAAGzAQEAAAAEtAEBAAAABLUBAQAAAAG2AQEAAAABtwEBAAAAAbgBAQAAAAG5AQEA_wEAIboBAQAAAAG7AQEAAAABvAEBAAAAAQmpAQAAgAIAMKoBAADiAQAQqwEAAIACADCsAQEAgQIAIa0BAQCBAgAhrgEBAIECACGvAUAAggIAIbABQACCAgAhsQFAAIICACELsgEBAAAAAbMBAQAAAAS0AQEAAAAEtQEBAAAAAbYBAQAAAAG3AQEAAAABuAEBAAAAAbkBAQD_AQAhugEBAAAAAbsBAQAAAAG8AQEAAAABCLIBQAAAAAGzAUAAAAAEtAFAAAAABLUBQAAAAAG2AUAAAAABtwFAAAAAAbgBQAAAAAG5AUAA_QEAIRCpAQAAgwIAMKoBAADcAQAQqwEAAIMCADCsAQEA-QEAIbABQAD6AQAhsQFAAPoBACG9AQEA-QEAIb4BAQD5AQAhvwEBAPkBACHAAQEAhAIAIcEBAQCEAgAhwgEBAIQCACHDAUAAhQIAIcQBQACFAgAhxQEBAIQCACHGAQEAhAIAIQ4EAACHAgAgJQAAigIAICYAAIoCACCyAQEAAAABswEBAAAABbQBAQAAAAW1AQEAAAABtgEBAAAAAbcBAQAAAAG4AQEAAAABuQEBAIkCACG6AQEAAAABuwEBAAAAAbwBAQAAAAELBAAAhwIAICUAAIgCACAmAACIAgAgsgFAAAAAAbMBQAAAAAW0AUAAAAAFtQFAAAAAAbYBQAAAAAG3AUAAAAABuAFAAAAAAbkBQACGAgAhCwQAAIcCACAlAACIAgAgJgAAiAIAILIBQAAAAAGzAUAAAAAFtAFAAAAABbUBQAAAAAG2AUAAAAABtwFAAAAAAbgBQAAAAAG5AUAAhgIAIQiyAQIAAAABswECAAAABbQBAgAAAAW1AQIAAAABtgECAAAAAbcBAgAAAAG4AQIAAAABuQECAIcCACEIsgFAAAAAAbMBQAAAAAW0AUAAAAAFtQFAAAAAAbYBQAAAAAG3AUAAAAABuAFAAAAAAbkBQACIAgAhDgQAAIcCACAlAACKAgAgJgAAigIAILIBAQAAAAGzAQEAAAAFtAEBAAAABbUBAQAAAAG2AQEAAAABtwEBAAAAAbgBAQAAAAG5AQEAiQIAIboBAQAAAAG7AQEAAAABvAEBAAAAAQuyAQEAAAABswEBAAAABbQBAQAAAAW1AQEAAAABtgEBAAAAAbcBAQAAAAG4AQEAAAABuQEBAIoCACG6AQEAAAABuwEBAAAAAbwBAQAAAAELqQEAAIsCADCqAQAAxgEAEKsBAACLAgAwrAEBAPkBACGvAUAA-gEAIbABQAD6AQAhsQFAAPoBACG_AQEA-QEAIccBAQD5AQAhyAEBAIQCACHJAQEAhAIAIQypAQAAjAIAMKoBAACwAQAQqwEAAIwCADCsAQEA-QEAIbABQAD6AQAhsQFAAPoBACHKAQEA-QEAIcsBAQD5AQAhzAEgAI0CACHOAQAAjgLOASLQAQAAjwLQASLRAQEAhAIAIQUEAAD8AQAgJQAAlQIAICYAAJUCACCyASAAAAABuQEgAJQCACEHBAAA_AEAICUAAJMCACAmAACTAgAgsgEAAADOAQKzAQAAAM4BCLQBAAAAzgEIuQEAAJICzgEiBwQAAPwBACAlAACRAgAgJgAAkQIAILIBAAAA0AECswEAAADQAQi0AQAAANABCLkBAACQAtABIgcEAAD8AQAgJQAAkQIAICYAAJECACCyAQAAANABArMBAAAA0AEItAEAAADQAQi5AQAAkALQASIEsgEAAADQAQKzAQAAANABCLQBAAAA0AEIuQEAAJEC0AEiBwQAAPwBACAlAACTAgAgJgAAkwIAILIBAAAAzgECswEAAADOAQi0AQAAAM4BCLkBAACSAs4BIgSyAQAAAM4BArMBAAAAzgEItAEAAADOAQi5AQAAkwLOASIFBAAA_AEAICUAAJUCACAmAACVAgAgsgEgAAAAAbkBIACUAgAhArIBIAAAAAG5ASAAlQIAIRMDAACdAgAgBwAAmwIAIAgAAJwCACALAACeAgAgDQAAnwIAIA4AAJ8CACAPAACgAgAgqQEAAJYCADCqAQAAnQEAEKsBAACWAgAwrAEBAIECACGwAUAAggIAIbEBQACCAgAhygEBAIECACHLAQEAgQIAIcwBIACXAgAhzgEAAJgCzgEi0AEAAJkC0AEi0QEBAJoCACECsgEgAAAAAbkBIACVAgAhBLIBAAAAzgECswEAAADOAQi0AQAAAM4BCLkBAACTAs4BIgSyAQAAANABArMBAAAA0AEItAEAAADQAQi5AQAAkQLQASILsgEBAAAAAbMBAQAAAAW0AQEAAAAFtQEBAAAAAbYBAQAAAAG3AQEAAAABuAEBAAAAAbkBAQCKAgAhugEBAAAAAbsBAQAAAAG8AQEAAAABA9IBAAAHACDTAQAABwAg1AEAAAcAIAPSAQAACwAg0wEAAAsAINQBAAALACAD0gEAAAMAINMBAAADACDUAQAAAwAgA9IBAAAQACDTAQAAEAAg1AEAABAAIAPSAQAAFAAg0wEAABQAINQBAAAUACAD0gEAABkAINMBAAAZACDUAQAAGQAgCakBAAChAgAwqgEAAJcBABCrAQAAoQIAMKwBAQD5AQAhsAFAAPoBACHVAQIAogIAIdYBAQD5AQAh1wEBAPkBACHYAQEA-QEAIQ0EAAD8AQAgIwAApAIAICQAAPwBACAlAAD8AQAgJgAA_AEAILIBAgAAAAGzAQIAAAAEtAECAAAABLUBAgAAAAG2AQIAAAABtwECAAAAAbgBAgAAAAG5AQIAowIAIQ0EAAD8AQAgIwAApAIAICQAAPwBACAlAAD8AQAgJgAA_AEAILIBAgAAAAGzAQIAAAAEtAECAAAABLUBAgAAAAG2AQIAAAABtwECAAAAAbgBAgAAAAG5AQIAowIAIQiyAQgAAAABswEIAAAABLQBCAAAAAS1AQgAAAABtgEIAAAAAbcBCAAAAAG4AQgAAAABuQEIAKQCACEHqQEAAKUCADCqAQAAgQEAEKsBAAClAgAwrAEBAPkBACGwAUAA-gEAIcoBAQD5AQAh2QEBAIQCACEIAwAAnQIAIKkBAACmAgAwqgEAAG4AEKsBAACmAgAwrAEBAIECACGwAUAAggIAIcoBAQCBAgAh2QEBAJoCACEOqQEAAKcCADCqAQAAaAAQqwEAAKcCADCsAQEA-QEAIbABQAD6AQAhsQFAAPoBACHQAQAAqALbASLbAQEA-QEAIdwBCACpAgAh3QECAKICACHeAQEA-QEAId8BAQD5AQAh4AEBAPkBACHhAQEA-QEAIQcEAAD8AQAgJQAArAIAICYAAKwCACCyAQAAANsBArMBAAAA2wEItAEAAADbAQi5AQAAqwLbASINBAAA_AEAICMAAKQCACAkAACkAgAgJQAApAIAICYAAKQCACCyAQgAAAABswEIAAAABLQBCAAAAAS1AQgAAAABtgEIAAAAAbcBCAAAAAG4AQgAAAABuQEIAKoCACENBAAA_AEAICMAAKQCACAkAACkAgAgJQAApAIAICYAAKQCACCyAQgAAAABswEIAAAABLQBCAAAAAS1AQgAAAABtgEIAAAAAbcBCAAAAAG4AQgAAAABuQEIAKoCACEHBAAA_AEAICUAAKwCACAmAACsAgAgsgEAAADbAQKzAQAAANsBCLQBAAAA2wEIuQEAAKsC2wEiBLIBAAAA2wECswEAAADbAQi0AQAAANsBCLkBAACsAtsBIgipAQAArQIAMKoBAABSABCrAQAArQIAMKwBAQD5AQAhsAFAAPoBACHdAQIAogIAIeABAQD5AQAh4QEBAPkBACEOqQEAAK4CADCqAQAAPAAQqwEAAK4CADCsAQEA-QEAIbABQAD6AQAhsQFAAPoBACHKAQEA-QEAIdEBAQCEAgAh2QEBAPkBACHfAQEA-QEAIeIBCACpAgAh4wECAKICACHkAQEA-QEAIeUBAQD5AQAhAuABAQAAAAHhAQEAAAABCgkAALMCACAKAACyAgAgqQEAALACADCqAQAAGQAQqwEAALACADCsAQEAgQIAIbABQACCAgAh3QECALECACHgAQEAgQIAIeEBAQCBAgAhCLIBAgAAAAGzAQIAAAAEtAECAAAABLUBAgAAAAG2AQIAAAABtwECAAAAAbgBAgAAAAG5AQIA_AEAIRUDAACdAgAgBwAAmwIAIAgAAJwCACALAACeAgAgDQAAnwIAIA4AAJ8CACAPAACgAgAgqQEAAJYCADCqAQAAnQEAEKsBAACWAgAwrAEBAIECACGwAUAAggIAIbEBQACCAgAhygEBAIECACHLAQEAgQIAIcwBIACXAgAhzgEAAJgCzgEi0AEAAJkC0AEi0QEBAJoCACHnAQAAnQEAIOgBAACdAQAgFQUAALwCACALAACeAgAgDAAAsgIAIA8AAKACACAQAACfAgAgqQEAALsCADCqAQAAAwAQqwEAALsCADCsAQEAgQIAIbABQACCAgAhsQFAAIICACHKAQEAgQIAIdEBAQCaAgAh2QEBAIECACHfAQEAgQIAIeIBCAC2AgAh4wECALECACHkAQEAgQIAIeUBAQCBAgAh5wEAAAMAIOgBAAADACARCQAAswIAIAoAALICACAMAACyAgAgqQEAALQCADCqAQAAFAAQqwEAALQCADCsAQEAgQIAIbABQACCAgAhsQFAAIICACHQAQAAtQLbASLbAQEAgQIAIdwBCAC2AgAh3QECALECACHeAQEAgQIAId8BAQCBAgAh4AEBAIECACHhAQEAgQIAIQSyAQAAANsBArMBAAAA2wEItAEAAADbAQi5AQAArALbASIIsgEIAAAAAbMBCAAAAAS0AQgAAAAEtQEIAAAAAbYBCAAAAAG3AQgAAAABuAEIAAAAAbkBCACkAgAhCwkAALMCACAKAACyAgAgqQEAALcCADCqAQAAEAAQqwEAALcCADCsAQEAgQIAIbABQACCAgAh1QECALECACHWAQEAgQIAIdcBAQCBAgAh2AEBAIECACERBgAAsgIAIKkBAAC4AgAwqgEAAAsAEKsBAAC4AgAwrAEBAIECACGwAUAAggIAIbEBQACCAgAhvQEBAIECACG-AQEAgQIAIb8BAQCBAgAhwAEBAJoCACHBAQEAmgIAIcIBAQCaAgAhwwFAALkCACHEAUAAuQIAIcUBAQCaAgAhxgEBAJoCACEIsgFAAAAAAbMBQAAAAAW0AUAAAAAFtQFAAAAAAbYBQAAAAAG3AUAAAAABuAFAAAAAAbkBQACIAgAhDAYAALICACCpAQAAugIAMKoBAAAHABCrAQAAugIAMKwBAQCBAgAhrwFAAIICACGwAUAAggIAIbEBQACCAgAhvwEBAIECACHHAQEAgQIAIcgBAQCaAgAhyQEBAJoCACETBQAAvAIAIAsAAJ4CACAMAACyAgAgDwAAoAIAIBAAAJ8CACCpAQAAuwIAMKoBAAADABCrAQAAuwIAMKwBAQCBAgAhsAFAAIICACGxAUAAggIAIcoBAQCBAgAh0QEBAJoCACHZAQEAgQIAId8BAQCBAgAh4gEIALYCACHjAQIAsQIAIeQBAQCBAgAh5QEBAIECACEKAwAAnQIAIKkBAACmAgAwqgEAAG4AEKsBAACmAgAwrAEBAIECACGwAUAAggIAIcoBAQCBAgAh2QEBAJoCACHnAQAAbgAg6AEAAG4AIAAAAAHsAQEAAAABAewBQAAAAAEAAAAAAewBAQAAAAEB7AFAAAAAAQUdAADSBAAgHgAA1QQAIOkBAADTBAAg6gEAANQEACDvAQAAmgEAIAMdAADSBAAg6QEAANMEACDvAQAAmgEAIAAAAAUdAADNBAAgHgAA0AQAIOkBAADOBAAg6gEAAM8EACDvAQAAmgEAIAMdAADNBAAg6QEAAM4EACDvAQAAmgEAIAAAAAHsASAAAAABAewBAAAAzgECAewBAAAA0AECCx0AANUDADAeAADaAwAw6QEAANYDADDqAQAA1wMAMOsBAADYAwAg7AEAANkDADDtAQAA2QMAMO4BAADZAwAw7wEAANkDADDwAQAA2wMAMPEBAADcAwAwCx0AAMkDADAeAADOAwAw6QEAAMoDADDqAQAAywMAMOsBAADMAwAg7AEAAM0DADDtAQAAzQMAMO4BAADNAwAw7wEAAM0DADDwAQAAzwMAMPEBAADQAwAwCx0AAJYDADAeAACbAwAw6QEAAJcDADDqAQAAmAMAMOsBAACZAwAg7AEAAJoDADDtAQAAmgMAMO4BAACaAwAw7wEAAJoDADDwAQAAnAMAMPEBAACdAwAwCx0AAIgDADAeAACNAwAw6QEAAIkDADDqAQAAigMAMOsBAACLAwAg7AEAAIwDADDtAQAAjAMAMO4BAACMAwAw7wEAAIwDADDwAQAAjgMAMPEBAACPAwAwCx0AAP0CADAeAACBAwAw6QEAAP4CADDqAQAA_wIAMOsBAACAAwAg7AEAAO8CADDtAQAA7wIAMO4BAADvAgAw7wEAAO8CADDwAQAAggMAMPEBAADyAgAwCx0AAOsCADAeAADwAgAw6QEAAOwCADDqAQAA7QIAMOsBAADuAgAg7AEAAO8CADDtAQAA7wIAMO4BAADvAgAw7wEAAO8CADDwAQAA8QIAMPEBAADyAgAwCx0AANwCADAeAADhAgAw6QEAAN0CADDqAQAA3gIAMOsBAADfAgAg7AEAAOACADDtAQAA4AIAMO4BAADgAgAw7wEAAOACADDwAQAA4gIAMPEBAADjAgAwBQkAAOoCACCsAQEAAAABsAFAAAAAAd0BAgAAAAHgAQEAAAABAgAAABsAIB0AAOkCACADAAAAGwAgHQAA6QIAIB4AAOcCACABFgAAzAQAMAsJAACzAgAgCgAAsgIAIKkBAACwAgAwqgEAABkAEKsBAACwAgAwrAEBAAAAAbABQACCAgAh3QECALECACHgAQEAgQIAIeEBAQCBAgAh5gEAAK8CACACAAAAGwAgFgAA5wIAIAIAAADkAgAgFgAA5QIAIAipAQAA4wIAMKoBAADkAgAQqwEAAOMCADCsAQEAgQIAIbABQACCAgAh3QECALECACHgAQEAgQIAIeEBAQCBAgAhCKkBAADjAgAwqgEAAOQCABCrAQAA4wIAMKwBAQCBAgAhsAFAAIICACHdAQIAsQIAIeABAQCBAgAh4QEBAIECACEErAEBAMACACGwAUAAwQIAId0BAgDmAgAh4AEBAMACACEF7AECAAAAAfIBAgAAAAHzAQIAAAAB9AECAAAAAfUBAgAAAAEFCQAA6AIAIKwBAQDAAgAhsAFAAMECACHdAQIA5gIAIeABAQDAAgAhBR0AAMcEACAeAADKBAAg6QEAAMgEACDqAQAAyQQAIO8BAAABACAFCQAA6gIAIKwBAQAAAAGwAUAAAAAB3QECAAAAAeABAQAAAAEDHQAAxwQAIOkBAADIBAAg7wEAAAEAIAwJAAD7AgAgCgAA_AIAIKwBAQAAAAGwAUAAAAABsQFAAAAAAdABAAAA2wEC2wEBAAAAAdwBCAAAAAHdAQIAAAAB3gEBAAAAAeABAQAAAAHhAQEAAAABAgAAABYAIB0AAPoCACADAAAAFgAgHQAA-gIAIB4AAPcCACABFgAAxgQAMBEJAACzAgAgCgAAsgIAIAwAALICACCpAQAAtAIAMKoBAAAUABCrAQAAtAIAMKwBAQAAAAGwAUAAggIAIbEBQACCAgAh0AEAALUC2wEi2wEBAIECACHcAQgAtgIAId0BAgCxAgAh3gEBAIECACHfAQEAgQIAIeABAQCBAgAh4QEBAIECACECAAAAFgAgFgAA9wIAIAIAAADzAgAgFgAA9AIAIA6pAQAA8gIAMKoBAADzAgAQqwEAAPICADCsAQEAgQIAIbABQACCAgAhsQFAAIICACHQAQAAtQLbASLbAQEAgQIAIdwBCAC2AgAh3QECALECACHeAQEAgQIAId8BAQCBAgAh4AEBAIECACHhAQEAgQIAIQ6pAQAA8gIAMKoBAADzAgAQqwEAAPICADCsAQEAgQIAIbABQACCAgAhsQFAAIICACHQAQAAtQLbASLbAQEAgQIAIdwBCAC2AgAh3QECALECACHeAQEAgQIAId8BAQCBAgAh4AEBAIECACHhAQEAgQIAIQqsAQEAwAIAIbABQADBAgAhsQFAAMECACHQAQAA9QLbASLbAQEAwAIAIdwBCAD2AgAh3QECAOYCACHeAQEAwAIAIeABAQDAAgAh4QEBAMACACEB7AEAAADbAQIF7AEIAAAAAfIBCAAAAAHzAQgAAAAB9AEIAAAAAfUBCAAAAAEMCQAA-AIAIAoAAPkCACCsAQEAwAIAIbABQADBAgAhsQFAAMECACHQAQAA9QLbASLbAQEAwAIAIdwBCAD2AgAh3QECAOYCACHeAQEAwAIAIeABAQDAAgAh4QEBAMACACEFHQAAvgQAIB4AAMQEACDpAQAAvwQAIOoBAADDBAAg7wEAAAEAIAUdAAC8BAAgHgAAwQQAIOkBAAC9BAAg6gEAAMAEACDvAQAAmgEAIAwJAAD7AgAgCgAA_AIAIKwBAQAAAAGwAUAAAAABsQFAAAAAAdABAAAA2wEC2wEBAAAAAdwBCAAAAAHdAQIAAAAB3gEBAAAAAeABAQAAAAHhAQEAAAABAx0AAL4EACDpAQAAvwQAIO8BAAABACADHQAAvAQAIOkBAAC9BAAg7wEAAJoBACAMCQAA-wIAIAwAAIcDACCsAQEAAAABsAFAAAAAAbEBQAAAAAHQAQAAANsBAtsBAQAAAAHcAQgAAAAB3QECAAAAAd4BAQAAAAHfAQEAAAAB4AEBAAAAAQIAAAAWACAdAACGAwAgAwAAABYAIB0AAIYDACAeAACEAwAgARYAALsEADACAAAAFgAgFgAAhAMAIAIAAADzAgAgFgAAgwMAIAqsAQEAwAIAIbABQADBAgAhsQFAAMECACHQAQAA9QLbASLbAQEAwAIAIdwBCAD2AgAh3QECAOYCACHeAQEAwAIAId8BAQDAAgAh4AEBAMACACEMCQAA-AIAIAwAAIUDACCsAQEAwAIAIbABQADBAgAhsQFAAMECACHQAQAA9QLbASLbAQEAwAIAIdwBCAD2AgAh3QECAOYCACHeAQEAwAIAId8BAQDAAgAh4AEBAMACACEFHQAAtgQAIB4AALkEACDpAQAAtwQAIOoBAAC4BAAg7wEAAJoBACAMCQAA-wIAIAwAAIcDACCsAQEAAAABsAFAAAAAAbEBQAAAAAHQAQAAANsBAtsBAQAAAAHcAQgAAAAB3QECAAAAAd4BAQAAAAHfAQEAAAAB4AEBAAAAAQMdAAC2BAAg6QEAALcEACDvAQAAmgEAIAYJAACVAwAgrAEBAAAAAbABQAAAAAHVAQIAAAAB1gEBAAAAAdcBAQAAAAECAAAAEgAgHQAAlAMAIAMAAAASACAdAACUAwAgHgAAkgMAIAEWAAC1BAAwCwkAALMCACAKAACyAgAgqQEAALcCADCqAQAAEAAQqwEAALcCADCsAQEAAAABsAFAAIICACHVAQIAsQIAIdYBAQCBAgAh1wEBAIECACHYAQEAgQIAIQIAAAASACAWAACSAwAgAgAAAJADACAWAACRAwAgCakBAACPAwAwqgEAAJADABCrAQAAjwMAMKwBAQCBAgAhsAFAAIICACHVAQIAsQIAIdYBAQCBAgAh1wEBAIECACHYAQEAgQIAIQmpAQAAjwMAMKoBAACQAwAQqwEAAI8DADCsAQEAgQIAIbABQACCAgAh1QECALECACHWAQEAgQIAIdcBAQCBAgAh2AEBAIECACEFrAEBAMACACGwAUAAwQIAIdUBAgDmAgAh1gEBAMACACHXAQEAwAIAIQYJAACTAwAgrAEBAMACACGwAUAAwQIAIdUBAgDmAgAh1gEBAMACACHXAQEAwAIAIQUdAACwBAAgHgAAswQAIOkBAACxBAAg6gEAALIEACDvAQAAAQAgBgkAAJUDACCsAQEAAAABsAFAAAAAAdUBAgAAAAHWAQEAAAAB1wEBAAAAAQMdAACwBAAg6QEAALEEACDvAQAAAQAgDgUAAMUDACALAADGAwAgDwAAyAMAIBAAAMcDACCsAQEAAAABsAFAAAAAAbEBQAAAAAHKAQEAAAAB0QEBAAAAAdkBAQAAAAHiAQgAAAAB4wECAAAAAeQBAQAAAAHlAQEAAAABAgAAAAEAIB0AAMQDACADAAAAAQAgHQAAxAMAIB4AAKADACABFgAArwQAMBMFAAC8AgAgCwAAngIAIAwAALICACAPAACgAgAgEAAAnwIAIKkBAAC7AgAwqgEAAAMAEKsBAAC7AgAwrAEBAAAAAbABQACCAgAhsQFAAIICACHKAQEAgQIAIdEBAQCaAgAh2QEBAIECACHfAQEAgQIAIeIBCAC2AgAh4wECALECACHkAQEAgQIAIeUBAQCBAgAhAgAAAAEAIBYAAKADACACAAAAngMAIBYAAJ8DACAOqQEAAJ0DADCqAQAAngMAEKsBAACdAwAwrAEBAIECACGwAUAAggIAIbEBQACCAgAhygEBAIECACHRAQEAmgIAIdkBAQCBAgAh3wEBAIECACHiAQgAtgIAIeMBAgCxAgAh5AEBAIECACHlAQEAgQIAIQ6pAQAAnQMAMKoBAACeAwAQqwEAAJ0DADCsAQEAgQIAIbABQACCAgAhsQFAAIICACHKAQEAgQIAIdEBAQCaAgAh2QEBAIECACHfAQEAgQIAIeIBCAC2AgAh4wECALECACHkAQEAgQIAIeUBAQCBAgAhCqwBAQDAAgAhsAFAAMECACGxAUAAwQIAIcoBAQDAAgAh0QEBAMYCACHZAQEAwAIAIeIBCAD2AgAh4wECAOYCACHkAQEAwAIAIeUBAQDAAgAhDgUAAKEDACALAACiAwAgDwAApAMAIBAAAKMDACCsAQEAwAIAIbABQADBAgAhsQFAAMECACHKAQEAwAIAIdEBAQDGAgAh2QEBAMACACHiAQgA9gIAIeMBAgDmAgAh5AEBAMACACHlAQEAwAIAIQUdAACdBAAgHgAArQQAIOkBAACeBAAg6gEAAKwEACDvAQAAawAgCx0AALkDADAeAAC9AwAw6QEAALoDADDqAQAAuwMAMOsBAAC8AwAg7AEAAIwDADDtAQAAjAMAMO4BAACMAwAw7wEAAIwDADDwAQAAvgMAMPEBAACPAwAwCx0AALADADAeAAC0AwAw6QEAALEDADDqAQAAsgMAMOsBAACzAwAg7AEAAO8CADDtAQAA7wIAMO4BAADvAgAw7wEAAO8CADDwAQAAtQMAMPEBAADyAgAwCx0AAKUDADAeAACpAwAw6QEAAKYDADDqAQAApwMAMOsBAACoAwAg7AEAAOACADDtAQAA4AIAMO4BAADgAgAw7wEAAOACADDwAQAAqgMAMPEBAADjAgAwBQoAAK8DACCsAQEAAAABsAFAAAAAAd0BAgAAAAHhAQEAAAABAgAAABsAIB0AAK4DACADAAAAGwAgHQAArgMAIB4AAKwDACABFgAAqwQAMAIAAAAbACAWAACsAwAgAgAAAOQCACAWAACrAwAgBKwBAQDAAgAhsAFAAMECACHdAQIA5gIAIeEBAQDAAgAhBQoAAK0DACCsAQEAwAIAIbABQADBAgAh3QECAOYCACHhAQEAwAIAIQUdAACmBAAgHgAAqQQAIOkBAACnBAAg6gEAAKgEACDvAQAAmgEAIAUKAACvAwAgrAEBAAAAAbABQAAAAAHdAQIAAAAB4QEBAAAAAQMdAACmBAAg6QEAAKcEACDvAQAAmgEAIAwKAAD8AgAgDAAAhwMAIKwBAQAAAAGwAUAAAAABsQFAAAAAAdABAAAA2wEC2wEBAAAAAdwBCAAAAAHdAQIAAAAB3gEBAAAAAd8BAQAAAAHhAQEAAAABAgAAABYAIB0AALgDACADAAAAFgAgHQAAuAMAIB4AALcDACABFgAApQQAMAIAAAAWACAWAAC3AwAgAgAAAPMCACAWAAC2AwAgCqwBAQDAAgAhsAFAAMECACGxAUAAwQIAIdABAAD1AtsBItsBAQDAAgAh3AEIAPYCACHdAQIA5gIAId4BAQDAAgAh3wEBAMACACHhAQEAwAIAIQwKAAD5AgAgDAAAhQMAIKwBAQDAAgAhsAFAAMECACGxAUAAwQIAIdABAAD1AtsBItsBAQDAAgAh3AEIAPYCACHdAQIA5gIAId4BAQDAAgAh3wEBAMACACHhAQEAwAIAIQwKAAD8AgAgDAAAhwMAIKwBAQAAAAGwAUAAAAABsQFAAAAAAdABAAAA2wEC2wEBAAAAAdwBCAAAAAHdAQIAAAAB3gEBAAAAAd8BAQAAAAHhAQEAAAABBgoAAMMDACCsAQEAAAABsAFAAAAAAdUBAgAAAAHWAQEAAAAB2AEBAAAAAQIAAAASACAdAADCAwAgAwAAABIAIB0AAMIDACAeAADAAwAgARYAAKQEADACAAAAEgAgFgAAwAMAIAIAAACQAwAgFgAAvwMAIAWsAQEAwAIAIbABQADBAgAh1QECAOYCACHWAQEAwAIAIdgBAQDAAgAhBgoAAMEDACCsAQEAwAIAIbABQADBAgAh1QECAOYCACHWAQEAwAIAIdgBAQDAAgAhBR0AAJ8EACAeAACiBAAg6QEAAKAEACDqAQAAoQQAIO8BAACaAQAgBgoAAMMDACCsAQEAAAABsAFAAAAAAdUBAgAAAAHWAQEAAAAB2AEBAAAAAQMdAACfBAAg6QEAAKAEACDvAQAAmgEAIA4FAADFAwAgCwAAxgMAIA8AAMgDACAQAADHAwAgrAEBAAAAAbABQAAAAAGxAUAAAAABygEBAAAAAdEBAQAAAAHZAQEAAAAB4gEIAAAAAeMBAgAAAAHkAQEAAAAB5QEBAAAAAQMdAACdBAAg6QEAAJ4EACDvAQAAawAgBB0AALkDADDpAQAAugMAMOsBAAC8AwAg7wEAAIwDADAEHQAAsAMAMOkBAACxAwAw6wEAALMDACDvAQAA7wIAMAQdAAClAwAw6QEAAKYDADDrAQAAqAMAIO8BAADgAgAwDKwBAQAAAAGwAUAAAAABsQFAAAAAAb0BAQAAAAG-AQEAAAABwAEBAAAAAcEBAQAAAAHCAQEAAAABwwFAAAAAAcQBQAAAAAHFAQEAAAABxgEBAAAAAQIAAAANACAdAADUAwAgAwAAAA0AIB0AANQDACAeAADTAwAgARYAAJwEADARBgAAsgIAIKkBAAC4AgAwqgEAAAsAEKsBAAC4AgAwrAEBAAAAAbABQACCAgAhsQFAAIICACG9AQEAgQIAIb4BAQCBAgAhvwEBAIECACHAAQEAmgIAIcEBAQCaAgAhwgEBAJoCACHDAUAAuQIAIcQBQAC5AgAhxQEBAJoCACHGAQEAmgIAIQIAAAANACAWAADTAwAgAgAAANEDACAWAADSAwAgEKkBAADQAwAwqgEAANEDABCrAQAA0AMAMKwBAQCBAgAhsAFAAIICACGxAUAAggIAIb0BAQCBAgAhvgEBAIECACG_AQEAgQIAIcABAQCaAgAhwQEBAJoCACHCAQEAmgIAIcMBQAC5AgAhxAFAALkCACHFAQEAmgIAIcYBAQCaAgAhEKkBAADQAwAwqgEAANEDABCrAQAA0AMAMKwBAQCBAgAhsAFAAIICACGxAUAAggIAIb0BAQCBAgAhvgEBAIECACG_AQEAgQIAIcABAQCaAgAhwQEBAJoCACHCAQEAmgIAIcMBQAC5AgAhxAFAALkCACHFAQEAmgIAIcYBAQCaAgAhDKwBAQDAAgAhsAFAAMECACGxAUAAwQIAIb0BAQDAAgAhvgEBAMACACHAAQEAxgIAIcEBAQDGAgAhwgEBAMYCACHDAUAAxwIAIcQBQADHAgAhxQEBAMYCACHGAQEAxgIAIQysAQEAwAIAIbABQADBAgAhsQFAAMECACG9AQEAwAIAIb4BAQDAAgAhwAEBAMYCACHBAQEAxgIAIcIBAQDGAgAhwwFAAMcCACHEAUAAxwIAIcUBAQDGAgAhxgEBAMYCACEMrAEBAAAAAbABQAAAAAGxAUAAAAABvQEBAAAAAb4BAQAAAAHAAQEAAAABwQEBAAAAAcIBAQAAAAHDAUAAAAABxAFAAAAAAcUBAQAAAAHGAQEAAAABB6wBAQAAAAGvAUAAAAABsAFAAAAAAbEBQAAAAAHHAQEAAAAByAEBAAAAAckBAQAAAAECAAAACQAgHQAA4AMAIAMAAAAJACAdAADgAwAgHgAA3wMAIAEWAACbBAAwDAYAALICACCpAQAAugIAMKoBAAAHABCrAQAAugIAMKwBAQAAAAGvAUAAggIAIbABQACCAgAhsQFAAIICACG_AQEAgQIAIccBAQAAAAHIAQEAmgIAIckBAQCaAgAhAgAAAAkAIBYAAN8DACACAAAA3QMAIBYAAN4DACALqQEAANwDADCqAQAA3QMAEKsBAADcAwAwrAEBAIECACGvAUAAggIAIbABQACCAgAhsQFAAIICACG_AQEAgQIAIccBAQCBAgAhyAEBAJoCACHJAQEAmgIAIQupAQAA3AMAMKoBAADdAwAQqwEAANwDADCsAQEAgQIAIa8BQACCAgAhsAFAAIICACGxAUAAggIAIb8BAQCBAgAhxwEBAIECACHIAQEAmgIAIckBAQCaAgAhB6wBAQDAAgAhrwFAAMECACGwAUAAwQIAIbEBQADBAgAhxwEBAMACACHIAQEAxgIAIckBAQDGAgAhB6wBAQDAAgAhrwFAAMECACGwAUAAwQIAIbEBQADBAgAhxwEBAMACACHIAQEAxgIAIckBAQDGAgAhB6wBAQAAAAGvAUAAAAABsAFAAAAAAbEBQAAAAAHHAQEAAAAByAEBAAAAAckBAQAAAAEEHQAA1QMAMOkBAADWAwAw6wEAANgDACDvAQAA2QMAMAQdAADJAwAw6QEAAMoDADDrAQAAzAMAIO8BAADNAwAwBB0AAJYDADDpAQAAlwMAMOsBAACZAwAg7wEAAJoDADAEHQAAiAMAMOkBAACJAwAw6wEAAIsDACDvAQAAjAMAMAQdAAD9AgAw6QEAAP4CADDrAQAAgAMAIO8BAADvAgAwBB0AAOsCADDpAQAA7AIAMOsBAADuAgAg7wEAAO8CADAEHQAA3AIAMOkBAADdAgAw6wEAAN8CACDvAQAA4AIAMAAAAAAAAAAAAAAAAAAACx0AAPcDADAeAAD7AwAw6QEAAPgDADDqAQAA-QMAMOsBAAD6AwAg7AEAAJoDADDtAQAAmgMAMO4BAACaAwAw7wEAAJoDADDwAQAA_AMAMPEBAACdAwAwDgsAAMYDACAMAACBBAAgDwAAyAMAIBAAAMcDACCsAQEAAAABsAFAAAAAAbEBQAAAAAHKAQEAAAAB0QEBAAAAAdkBAQAAAAHfAQEAAAAB4gEIAAAAAeMBAgAAAAHkAQEAAAABAgAAAAEAIB0AAIAEACADAAAAAQAgHQAAgAQAIB4AAP4DACABFgAAmgQAMAIAAAABACAWAAD-AwAgAgAAAJ4DACAWAAD9AwAgCqwBAQDAAgAhsAFAAMECACGxAUAAwQIAIcoBAQDAAgAh0QEBAMYCACHZAQEAwAIAId8BAQDAAgAh4gEIAPYCACHjAQIA5gIAIeQBAQDAAgAhDgsAAKIDACAMAAD_AwAgDwAApAMAIBAAAKMDACCsAQEAwAIAIbABQADBAgAhsQFAAMECACHKAQEAwAIAIdEBAQDGAgAh2QEBAMACACHfAQEAwAIAIeIBCAD2AgAh4wECAOYCACHkAQEAwAIAIQUdAACVBAAgHgAAmAQAIOkBAACWBAAg6gEAAJcEACDvAQAAmgEAIA4LAADGAwAgDAAAgQQAIA8AAMgDACAQAADHAwAgrAEBAAAAAbABQAAAAAGxAUAAAAABygEBAAAAAdEBAQAAAAHZAQEAAAAB3wEBAAAAAeIBCAAAAAHjAQIAAAAB5AEBAAAAAQMdAACVBAAg6QEAAJYEACDvAQAAmgEAIAQdAAD3AwAw6QEAAPgDADDrAQAA-gMAIO8BAACaAwAwAAAAAAAAAAAAAAAAAAAACAMAAOoDACAHAADoAwAgCAAA6QMAIAsAAOsDACANAADsAwAgDgAA7AMAIA8AAO0DACDRAQAAwgIAIAYFAACUBAAgCwAA6wMAIAwAAJIEACAPAADtAwAgEAAA7AMAINEBAADCAgAgAgMAAOoDACDZAQAAwgIAIA8HAADhAwAgCAAA4gMAIAsAAOQDACANAADlAwAgDgAA5gMAIA8AAOcDACCsAQEAAAABsAFAAAAAAbEBQAAAAAHKAQEAAAABywEBAAAAAcwBIAAAAAHOAQAAAM4BAtABAAAA0AEC0QEBAAAAAQIAAACaAQAgHQAAlQQAIAMAAACdAQAgHQAAlQQAIB4AAJkEACARAAAAnQEAIAcAANUCACAIAADWAgAgCwAA2AIAIA0AANkCACAOAADaAgAgDwAA2wIAIBYAAJkEACCsAQEAwAIAIbABQADBAgAhsQFAAMECACHKAQEAwAIAIcsBAQDAAgAhzAEgANICACHOAQAA0wLOASLQAQAA1ALQASLRAQEAxgIAIQ8HAADVAgAgCAAA1gIAIAsAANgCACANAADZAgAgDgAA2gIAIA8AANsCACCsAQEAwAIAIbABQADBAgAhsQFAAMECACHKAQEAwAIAIcsBAQDAAgAhzAEgANICACHOAQAA0wLOASLQAQAA1ALQASLRAQEAxgIAIQqsAQEAAAABsAFAAAAAAbEBQAAAAAHKAQEAAAAB0QEBAAAAAdkBAQAAAAHfAQEAAAAB4gEIAAAAAeMBAgAAAAHkAQEAAAABB6wBAQAAAAGvAUAAAAABsAFAAAAAAbEBQAAAAAHHAQEAAAAByAEBAAAAAckBAQAAAAEMrAEBAAAAAbABQAAAAAGxAUAAAAABvQEBAAAAAb4BAQAAAAHAAQEAAAABwQEBAAAAAcIBAQAAAAHDAUAAAAABxAFAAAAAAcUBAQAAAAHGAQEAAAABBKwBAQAAAAGwAUAAAAABygEBAAAAAdkBAQAAAAECAAAAawAgHQAAnQQAIA8DAADjAwAgBwAA4QMAIAgAAOIDACANAADlAwAgDgAA5gMAIA8AAOcDACCsAQEAAAABsAFAAAAAAbEBQAAAAAHKAQEAAAABywEBAAAAAcwBIAAAAAHOAQAAAM4BAtABAAAA0AEC0QEBAAAAAQIAAACaAQAgHQAAnwQAIAMAAACdAQAgHQAAnwQAIB4AAKMEACARAAAAnQEAIAMAANcCACAHAADVAgAgCAAA1gIAIA0AANkCACAOAADaAgAgDwAA2wIAIBYAAKMEACCsAQEAwAIAIbABQADBAgAhsQFAAMECACHKAQEAwAIAIcsBAQDAAgAhzAEgANICACHOAQAA0wLOASLQAQAA1ALQASLRAQEAxgIAIQ8DAADXAgAgBwAA1QIAIAgAANYCACANAADZAgAgDgAA2gIAIA8AANsCACCsAQEAwAIAIbABQADBAgAhsQFAAMECACHKAQEAwAIAIcsBAQDAAgAhzAEgANICACHOAQAA0wLOASLQAQAA1ALQASLRAQEAxgIAIQWsAQEAAAABsAFAAAAAAdUBAgAAAAHWAQEAAAAB2AEBAAAAAQqsAQEAAAABsAFAAAAAAbEBQAAAAAHQAQAAANsBAtsBAQAAAAHcAQgAAAAB3QECAAAAAd4BAQAAAAHfAQEAAAAB4QEBAAAAAQ8DAADjAwAgBwAA4QMAIAgAAOIDACALAADkAwAgDQAA5QMAIA4AAOYDACCsAQEAAAABsAFAAAAAAbEBQAAAAAHKAQEAAAABywEBAAAAAcwBIAAAAAHOAQAAAM4BAtABAAAA0AEC0QEBAAAAAQIAAACaAQAgHQAApgQAIAMAAACdAQAgHQAApgQAIB4AAKoEACARAAAAnQEAIAMAANcCACAHAADVAgAgCAAA1gIAIAsAANgCACANAADZAgAgDgAA2gIAIBYAAKoEACCsAQEAwAIAIbABQADBAgAhsQFAAMECACHKAQEAwAIAIcsBAQDAAgAhzAEgANICACHOAQAA0wLOASLQAQAA1ALQASLRAQEAxgIAIQ8DAADXAgAgBwAA1QIAIAgAANYCACALAADYAgAgDQAA2QIAIA4AANoCACCsAQEAwAIAIbABQADBAgAhsQFAAMECACHKAQEAwAIAIcsBAQDAAgAhzAEgANICACHOAQAA0wLOASLQAQAA1ALQASLRAQEAxgIAIQSsAQEAAAABsAFAAAAAAd0BAgAAAAHhAQEAAAABAwAAAG4AIB0AAJ0EACAeAACuBAAgBgAAAG4AIBYAAK4EACCsAQEAwAIAIbABQADBAgAhygEBAMACACHZAQEAxgIAIQSsAQEAwAIAIbABQADBAgAhygEBAMACACHZAQEAxgIAIQqsAQEAAAABsAFAAAAAAbEBQAAAAAHKAQEAAAAB0QEBAAAAAdkBAQAAAAHiAQgAAAAB4wECAAAAAeQBAQAAAAHlAQEAAAABDwUAAMUDACAMAACBBAAgDwAAyAMAIBAAAMcDACCsAQEAAAABsAFAAAAAAbEBQAAAAAHKAQEAAAAB0QEBAAAAAdkBAQAAAAHfAQEAAAAB4gEIAAAAAeMBAgAAAAHkAQEAAAAB5QEBAAAAAQIAAAABACAdAACwBAAgAwAAAAMAIB0AALAEACAeAAC0BAAgEQAAAAMAIAUAAKEDACAMAAD_AwAgDwAApAMAIBAAAKMDACAWAAC0BAAgrAEBAMACACGwAUAAwQIAIbEBQADBAgAhygEBAMACACHRAQEAxgIAIdkBAQDAAgAh3wEBAMACACHiAQgA9gIAIeMBAgDmAgAh5AEBAMACACHlAQEAwAIAIQ8FAAChAwAgDAAA_wMAIA8AAKQDACAQAACjAwAgrAEBAMACACGwAUAAwQIAIbEBQADBAgAhygEBAMACACHRAQEAxgIAIdkBAQDAAgAh3wEBAMACACHiAQgA9gIAIeMBAgDmAgAh5AEBAMACACHlAQEAwAIAIQWsAQEAAAABsAFAAAAAAdUBAgAAAAHWAQEAAAAB1wEBAAAAAQ8DAADjAwAgBwAA4QMAIAgAAOIDACALAADkAwAgDQAA5QMAIA8AAOcDACCsAQEAAAABsAFAAAAAAbEBQAAAAAHKAQEAAAABywEBAAAAAcwBIAAAAAHOAQAAAM4BAtABAAAA0AEC0QEBAAAAAQIAAACaAQAgHQAAtgQAIAMAAACdAQAgHQAAtgQAIB4AALoEACARAAAAnQEAIAMAANcCACAHAADVAgAgCAAA1gIAIAsAANgCACANAADZAgAgDwAA2wIAIBYAALoEACCsAQEAwAIAIbABQADBAgAhsQFAAMECACHKAQEAwAIAIcsBAQDAAgAhzAEgANICACHOAQAA0wLOASLQAQAA1ALQASLRAQEAxgIAIQ8DAADXAgAgBwAA1QIAIAgAANYCACALAADYAgAgDQAA2QIAIA8AANsCACCsAQEAwAIAIbABQADBAgAhsQFAAMECACHKAQEAwAIAIcsBAQDAAgAhzAEgANICACHOAQAA0wLOASLQAQAA1ALQASLRAQEAxgIAIQqsAQEAAAABsAFAAAAAAbEBQAAAAAHQAQAAANsBAtsBAQAAAAHcAQgAAAAB3QECAAAAAd4BAQAAAAHfAQEAAAAB4AEBAAAAAQ8DAADjAwAgBwAA4QMAIAgAAOIDACALAADkAwAgDgAA5gMAIA8AAOcDACCsAQEAAAABsAFAAAAAAbEBQAAAAAHKAQEAAAABywEBAAAAAcwBIAAAAAHOAQAAAM4BAtABAAAA0AEC0QEBAAAAAQIAAACaAQAgHQAAvAQAIA8FAADFAwAgCwAAxgMAIAwAAIEEACAPAADIAwAgrAEBAAAAAbABQAAAAAGxAUAAAAABygEBAAAAAdEBAQAAAAHZAQEAAAAB3wEBAAAAAeIBCAAAAAHjAQIAAAAB5AEBAAAAAeUBAQAAAAECAAAAAQAgHQAAvgQAIAMAAACdAQAgHQAAvAQAIB4AAMIEACARAAAAnQEAIAMAANcCACAHAADVAgAgCAAA1gIAIAsAANgCACAOAADaAgAgDwAA2wIAIBYAAMIEACCsAQEAwAIAIbABQADBAgAhsQFAAMECACHKAQEAwAIAIcsBAQDAAgAhzAEgANICACHOAQAA0wLOASLQAQAA1ALQASLRAQEAxgIAIQ8DAADXAgAgBwAA1QIAIAgAANYCACALAADYAgAgDgAA2gIAIA8AANsCACCsAQEAwAIAIbABQADBAgAhsQFAAMECACHKAQEAwAIAIcsBAQDAAgAhzAEgANICACHOAQAA0wLOASLQAQAA1ALQASLRAQEAxgIAIQMAAAADACAdAAC-BAAgHgAAxQQAIBEAAAADACAFAAChAwAgCwAAogMAIAwAAP8DACAPAACkAwAgFgAAxQQAIKwBAQDAAgAhsAFAAMECACGxAUAAwQIAIcoBAQDAAgAh0QEBAMYCACHZAQEAwAIAId8BAQDAAgAh4gEIAPYCACHjAQIA5gIAIeQBAQDAAgAh5QEBAMACACEPBQAAoQMAIAsAAKIDACAMAAD_AwAgDwAApAMAIKwBAQDAAgAhsAFAAMECACGxAUAAwQIAIcoBAQDAAgAh0QEBAMYCACHZAQEAwAIAId8BAQDAAgAh4gEIAPYCACHjAQIA5gIAIeQBAQDAAgAh5QEBAMACACEKrAEBAAAAAbABQAAAAAGxAUAAAAAB0AEAAADbAQLbAQEAAAAB3AEIAAAAAd0BAgAAAAHeAQEAAAAB4AEBAAAAAeEBAQAAAAEPBQAAxQMAIAsAAMYDACAMAACBBAAgEAAAxwMAIKwBAQAAAAGwAUAAAAABsQFAAAAAAcoBAQAAAAHRAQEAAAAB2QEBAAAAAd8BAQAAAAHiAQgAAAAB4wECAAAAAeQBAQAAAAHlAQEAAAABAgAAAAEAIB0AAMcEACADAAAAAwAgHQAAxwQAIB4AAMsEACARAAAAAwAgBQAAoQMAIAsAAKIDACAMAAD_AwAgEAAAowMAIBYAAMsEACCsAQEAwAIAIbABQADBAgAhsQFAAMECACHKAQEAwAIAIdEBAQDGAgAh2QEBAMACACHfAQEAwAIAIeIBCAD2AgAh4wECAOYCACHkAQEAwAIAIeUBAQDAAgAhDwUAAKEDACALAACiAwAgDAAA_wMAIBAAAKMDACCsAQEAwAIAIbABQADBAgAhsQFAAMECACHKAQEAwAIAIdEBAQDGAgAh2QEBAMACACHfAQEAwAIAIeIBCAD2AgAh4wECAOYCACHkAQEAwAIAIeUBAQDAAgAhBKwBAQAAAAGwAUAAAAAB3QECAAAAAeABAQAAAAEPAwAA4wMAIAgAAOIDACALAADkAwAgDQAA5QMAIA4AAOYDACAPAADnAwAgrAEBAAAAAbABQAAAAAGxAUAAAAABygEBAAAAAcsBAQAAAAHMASAAAAABzgEAAADOAQLQAQAAANABAtEBAQAAAAECAAAAmgEAIB0AAM0EACADAAAAnQEAIB0AAM0EACAeAADRBAAgEQAAAJ0BACADAADXAgAgCAAA1gIAIAsAANgCACANAADZAgAgDgAA2gIAIA8AANsCACAWAADRBAAgrAEBAMACACGwAUAAwQIAIbEBQADBAgAhygEBAMACACHLAQEAwAIAIcwBIADSAgAhzgEAANMCzgEi0AEAANQC0AEi0QEBAMYCACEPAwAA1wIAIAgAANYCACALAADYAgAgDQAA2QIAIA4AANoCACAPAADbAgAgrAEBAMACACGwAUAAwQIAIbEBQADBAgAhygEBAMACACHLAQEAwAIAIcwBIADSAgAhzgEAANMCzgEi0AEAANQC0AEi0QEBAMYCACEPAwAA4wMAIAcAAOEDACALAADkAwAgDQAA5QMAIA4AAOYDACAPAADnAwAgrAEBAAAAAbABQAAAAAGxAUAAAAABygEBAAAAAcsBAQAAAAHMASAAAAABzgEAAADOAQLQAQAAANABAtEBAQAAAAECAAAAmgEAIB0AANIEACADAAAAnQEAIB0AANIEACAeAADWBAAgEQAAAJ0BACADAADXAgAgBwAA1QIAIAsAANgCACANAADZAgAgDgAA2gIAIA8AANsCACAWAADWBAAgrAEBAMACACGwAUAAwQIAIbEBQADBAgAhygEBAMACACHLAQEAwAIAIcwBIADSAgAhzgEAANMCzgEi0AEAANQC0AEi0QEBAMYCACEPAwAA1wIAIAcAANUCACALAADYAgAgDQAA2QIAIA4AANoCACAPAADbAgAgrAEBAMACACGwAUAAwQIAIbEBQADBAgAhygEBAMACACHLAQEAwAIAIcwBIADSAgAhzgEAANMCzgEi0AEAANQC0AEi0QEBAMYCACEGBAALBQACCyQHDAAEDyYJECUIAgMFAQQAAwEDBgAIAw8BBAAKBwoFCA4GCxMHDRcIDhgIDxwJAQYABAEGAAQCCQABCgAEAwkAAQoABAwABAIJAAEKAAQHAx8ABx0ACB4ACyAADSEADiIADyMAAwsnAA8pABAoAAACBQACDAAEAgUAAgwABAUEABAjABEkABIlABMmABQAAAAAAAUEABAjABEkABIlABMmABQCCQABCgAEAgkAAQoABAUEABkjABokABslABwmAB0AAAAAAAUEABkjABokABslABwmAB0DCQABCgAEDAAEAwkAAQoABAwABAUEACIjACMkACQlACUmACYAAAAAAAUEACIjACMkACQlACUmACYAAAMEACslACwmAC0AAAADBAArJQAsJgAtAgkAAQoABAIJAAEKAAQFBAAyIwAzJAA0JQA1JgA2AAAAAAAFBAAyIwAzJAA0JQA1JgA2AAADBAA7JQA8JgA9AAAAAwQAOyUAPCYAPQEGAAQBBgAEAwQAQiUAQyYARAAAAAMEAEIlAEMmAEQBBgAEAQYABAMEAEklAEomAEsAAAADBABJJQBKJgBLAAAAAwQAUSUAUiYAUwAAAAMEAFElAFImAFMRAgESKgETKwEULAEVLQEXLwEYMQwZMg0aNAEbNgwcNw4fOAEgOQEhOgwnPQ8oPhUpPwkqQAkrQQksQgktQwkuRQkvRwwwSBYxSgkyTAwzTRc0Tgk1Twk2UAw3Uxg4VB45VQg6Vgg7Vwg8WAg9WQg-Wwg_XQxAXh9BYAhCYgxDYyBEZAhFZQhGZgxHaSFIaidJbAJKbQJLcAJMcQJNcgJOdAJPdgxQdyhReQJSewxTfClUfQJVfgJWfwxXggEqWIMBLlmEAQdahQEHW4YBB1yHAQddiAEHXooBB1-MAQxgjQEvYY8BB2KRAQxjkgEwZJMBB2WUAQdmlQEMZ5gBMWiZATdpmwEEapwBBGufAQRsoAEEbaEBBG6jAQRvpQEMcKYBOHGoAQRyqgEMc6sBOXSsAQR1rQEEdq4BDHexATp4sgE-ebMBBXq0AQV7tQEFfLYBBX23AQV-uQEFf7sBDIABvAE_gQG-AQWCAcABDIMBwQFAhAHCAQWFAcMBBYYBxAEMhwHHAUGIAcgBRYkByQEGigHKAQaLAcsBBowBzAEGjQHNAQaOAc8BBo8B0QEMkAHSAUaRAdQBBpIB1gEMkwHXAUeUAdgBBpUB2QEGlgHaAQyXAd0BSJgB3gFMmQHgAU2aAeEBTZsB5AFNnAHlAU2dAeYBTZ4B6AFNnwHqAQygAesBTqEB7QFNogHvAQyjAfABT6QB8QFNpQHyAU2mAfMBDKcB9gFQqAH3AVQ"
};
async function decodeBase64AsWasm(wasmBase64) {
  const { Buffer } = await import("buffer");
  const wasmArray = Buffer.from(wasmBase64, "base64");
  return new WebAssembly.Module(wasmArray);
}
config.compilerWasm = {
  getRuntime: async () => await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.mjs"),
  getQueryCompilerWasmModule: async () => {
    const { wasm } = await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.wasm-base64.mjs");
    return await decodeBase64AsWasm(wasm);
  },
  importName: "./query_compiler_fast_bg.js"
};
function getPrismaClientClass() {
  return runtime.getPrismaClient(config);
}

// generated/prisma/internal/prismaNamespace.ts
import * as runtime2 from "@prisma/client/runtime/client";
var getExtensionContext = runtime2.Extensions.getExtensionContext;
var NullTypes2 = {
  DbNull: runtime2.NullTypes.DbNull,
  JsonNull: runtime2.NullTypes.JsonNull,
  AnyNull: runtime2.NullTypes.AnyNull
};
var TransactionIsolationLevel = runtime2.makeStrictEnum({
  ReadUncommitted: "ReadUncommitted",
  ReadCommitted: "ReadCommitted",
  RepeatableRead: "RepeatableRead",
  Serializable: "Serializable"
});
var defineExtension = runtime2.Extensions.defineExtension;

// generated/prisma/client.ts
globalThis["__dirname"] = path.dirname(fileURLToPath(import.meta.url));
var PrismaClient = getPrismaClientClass();

// src/lib/prisma.ts
var connectionString = `${process.env.DATABASE_URL}`;
var adapter = new PrismaPg({ connectionString });
var prisma = new PrismaClient({ adapter });

// src/lib/auth.ts
var auth = betterAuth({
  database: prismaAdapter(prisma, {
    provider: "postgresql"
    // or "mysql", "postgresql", ...etc
  }),
  trustedOrigins: [process.env.APP_URL],
  emailAndPassword: {
    enabled: true,
    requireEmailVerification: false
  },
  socialProviders: {
    google: {
      clientId: process.env.GOOGLE_CLIENT_ID,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET
    }
  },
  user: {
    additionalFields: {
      role: {
        type: "string",
        defaultValue: "CUSTOMER"
      }
    }
  }
});

// src/app.ts
import cors from "cors";

// src/models/medicine/Medicine.routes.ts
import { Router } from "express";

// src/models/medicine/Medicine.services.ts
var createMedicine = async (medeicineData, sellerId) => {
  const result = await prisma.medicines.create({
    data: {
      ...medeicineData,
      Seller_id: sellerId
    },
    include: {
      Category: {
        select: {
          name: true,
          description: true
        }
      },
      Seller: {
        select: {
          name: true,
          email: true,
          id: true
        }
      }
    }
  });
  return result;
};
var getAllMedicine = async (query) => {
  const { name, manufacturer, category, minPrice, maxPrice } = query;
  const filter = {};
  if (name) {
    filter.name = { contains: name, mode: "insensitive" };
  }
  if (manufacturer) {
    filter.manufacturer = { contains: manufacturer, mode: "insensitive" };
  }
  if (category) {
    filter.category = { contains: category, mode: "insensitive" };
  }
  if (minPrice || maxPrice) {
    filter.price = {};
    if (minPrice) filter.price.gte = parseFloat(minPrice);
    if (maxPrice) filter.price.lte = parseFloat(maxPrice);
  }
  const result = await prisma.medicines.findMany({
    where: filter,
    include: {
      Category: {
        select: {
          name: true,
          description: true
        }
      },
      Seller: {
        select: {
          name: true,
          email: true,
          id: true
        }
      }
    }
  });
  return result;
};
var getMedicineById = async (id) => {
  const result = await prisma.medicines.findUnique({
    where: {
      id
    },
    // * if you want to show the catgeory or seller data
    include: {
      Category: true,
      Seller: true
    }
  });
  return result;
};
var updateMedicine = async (id, updateData) => {
  const result = await prisma.medicines.update({
    where: {
      id
    },
    data: updateData
  });
  return result;
};
var deleteMedicine = async (id) => {
  const result = await prisma.medicines.delete({
    where: {
      id
    }
  });
  return result;
};
var medicineServices = {
  createMedicine,
  getAllMedicine,
  getMedicineById,
  updateMedicine,
  deleteMedicine
};

// src/models/medicine/Medicine.controller.ts
var createMedicine2 = async (req, res) => {
  try {
    const sellerId = req.user?.id;
    if (!sellerId) {
      return res.status(401).json({
        message: "UNauthorized",
        success: false
      });
    }
    const result = await medicineServices.createMedicine(req.body, sellerId);
    res.status(200).json({
      message: "Medicine inserted successfully",
      success: true,
      data: result
    });
  } catch (error) {
    res.status(500).json({
      message: "Medcine insertion failed",
      success: false,
      error: error.message
    });
  }
};
var getAllMedicine2 = async (req, res) => {
  try {
    const query = req.query;
    const result = await medicineServices.getAllMedicine(query);
    if (!result || result.length === 0) {
      return res.status(200).json({
        message: "No medicine found",
        success: false
      });
    }
    res.status(200).json({
      message: "Medicine fetched successfully",
      success: true,
      data: result
    });
  } catch (error) {
    res.status(500).json({
      message: "Medicine fetched failed",
      success: false,
      error: error.message
    });
  }
};
var getMedicineById2 = async (req, res) => {
  try {
    const { id } = req.params;
    const result = await medicineServices.getMedicineById(id);
    res.status(200).json({
      message: "Medicine fetched successfully",
      success: true,
      data: result
    });
  } catch (err) {
    res.status(500).json({
      message: "Medicine fetched failed",
      success: false,
      error: err.message
    });
  }
};
var updateMedicine2 = async (req, res) => {
  try {
    const { id } = req.params;
    const result = await medicineServices.updateMedicine(id, req.body);
    res.status(200).json({
      message: "Medicine updated successfully",
      success: true,
      data: result
    });
  } catch (err) {
    res.status(500).json({
      message: "Medicine update failed",
      success: false,
      error: err.message
    });
  }
};
var deleteMedicine2 = async (req, res) => {
  try {
    const { id } = req.params;
    const result = await medicineServices.deleteMedicine(id);
    res.status(200).json({
      message: "Medicine deleted successfully",
      success: true,
      data: result
    });
  } catch (err) {
    res.status(500).json({
      message: "Delete failed",
      success: false,
      error: err.message
    });
  }
};
var MedicineController = {
  createMedicine: createMedicine2,
  getAllMedicine: getAllMedicine2,
  getMedicineById: getMedicineById2,
  updateMedicine: updateMedicine2,
  deleteMedicine: deleteMedicine2
};

// src/middleware/auth.middleware.ts
var AuthMiddleware = (...roles) => {
  return async (req, res, next) => {
    try {
      const session = await auth.api.getSession({
        headers: req.headers
      });
      console.log("Session", session);
      if (!session) {
        return res.status(401).json({
          message: "Unauthorized",
          success: false
        });
      }
      req.user = {
        id: session.user.id,
        email: session.user.email,
        name: session.user.name,
        role: session.user.role
      };
      if (roles.length > 0 && !roles.includes(req.user.role)) {
        return res.status(403).json({
          success: false,
          message: `Forbidden! Only ${roles.join(" or ")} can access this resource.`
        });
      }
      next();
    } catch (err) {
      next(err);
    }
  };
};
var auth_middleware_default = AuthMiddleware;

// src/models/medicine/Medicine.routes.ts
var router = Router();
router.post("/", auth_middleware_default("SELLER" /* SELLER */), MedicineController.createMedicine);
router.get("/", MedicineController.getAllMedicine);
router.get("/:id", MedicineController.getMedicineById);
router.patch("/:id", auth_middleware_default("SELLER" /* SELLER */), MedicineController.updateMedicine);
router.delete("/:id", auth_middleware_default("SELLER" /* SELLER */, "ADMIN" /* ADMIN */), MedicineController.deleteMedicine);
var medicineRouter = router;

// src/models/categories/categories.routes.ts
import { Router as Router2 } from "express";

// src/models/categories/categories.services.ts
var createCategories = async (categoryData) => {
  const result = await prisma.categories.create({
    data: categoryData
  });
  return result;
};
var updateCategories = async (id, categoryData) => {
  const result = await prisma.categories.update({
    where: {
      id
    },
    data: categoryData
  });
  return result;
};
var deleteCategories = async (id) => {
  const result = await prisma.categories.delete({
    where: {
      id
    }
  });
  return result;
};
var getCategories = async (categoryData) => {
  const result = await prisma.categories.findMany();
  return result;
};
var CategoriesServices = {
  createCategories,
  getCategories,
  updateCategories,
  deleteCategories
};

// src/models/categories/categories.controller.ts
var createCategories2 = async (req, res) => {
  try {
    const result = await CategoriesServices.createCategories(req.body);
    res.status(200).json({
      message: "Categories created successfully",
      success: true,
      data: result
    });
  } catch (error) {
    res.status(500).json({
      message: error.message,
      success: false
    });
  }
};
var getCategories2 = async (req, res) => {
  try {
    const result = await CategoriesServices.getCategories(req.body);
    if (!result || result.length === 0) {
      return res.status(200).json({
        message: "No categories found",
        success: false
      });
    }
    res.status(200).json({
      message: "Categories fetched successfully",
      success: true,
      data: result
    });
  } catch (error) {
    res.status(500).json({
      message: error.message,
      success: false
    });
  }
};
var UpdateCategories = async (req, res) => {
  try {
    const { id } = req.params;
    const result = await CategoriesServices.updateCategories(req.body, id);
    res.status(200).json({
      message: "Category updated successfully",
      success: true,
      data: result
    });
  } catch (err) {
    res.status(500).json({
      message: err.message,
      success: false
    });
  }
};
var deleteCategories2 = async (req, res) => {
  try {
    const { id } = req.params;
    const result = await CategoriesServices.deleteCategories(id);
    res.status(200).json({
      message: "Category deleted successfully",
      success: true,
      data: result
    });
  } catch (err) {
    res.status(500).json({
      message: err.message,
      success: false
    });
  }
};
var CategoriesController = {
  createCategories: createCategories2,
  getCategories: getCategories2,
  UpdateCategories,
  deleteCategories: deleteCategories2
};

// src/models/categories/categories.routes.ts
var router2 = Router2();
router2.post("/", auth_middleware_default("ADMIN" /* ADMIN */), CategoriesController.createCategories);
router2.get("/", CategoriesController.getCategories);
router2.patch("/:id", auth_middleware_default("ADMIN" /* ADMIN */), CategoriesController.UpdateCategories);
router2.delete("/:id", auth_middleware_default("ADMIN" /* ADMIN */), CategoriesController.deleteCategories);
var CategoriesRouter = router2;

// src/models/orders/orders.routes.ts
import { Router as Router3 } from "express";

// src/models/orders/orders.services.ts
var createOrder = async (orderData, customerId) => {
  const medicine = await prisma.medicines.findUnique({
    where: {
      id: orderData.medicine_id
    }
  });
  if (!medicine) {
    throw new Error("Medicine not found");
  }
  if (medicine.stock < orderData.quantity) {
    throw new Error("Out of stock");
  }
  const result = await prisma.orders.create({
    data: {
      quantity: orderData.quantity,
      paymentMethod: orderData.paymentMethod,
      Customer_id: customerId,
      Medicine_id: orderData.medicine_id,
      TotalPrice: medicine.price * orderData.quantity,
      Seller_id: medicine.Seller_id,
      status: "PENDING",
      shippingAddress: orderData.shippingAddress
    }
  });
  await prisma.medicines.update({
    where: {
      id: orderData.medicine_id
    },
    data: {
      stock: {
        decrement: orderData.quantity
      }
    }
  });
  return result;
};
var getCustomerOrders = async (customerId) => {
  const result = await prisma.orders.findMany({
    where: {
      Customer_id: customerId
    },
    include: {
      Medicine: true,
      Seller: true
    }
  });
  return result;
};
var getSelleOrders = async (sellerId) => {
  const result = await prisma.orders.findMany({
    where: {
      Seller_id: sellerId
    },
    include: {
      Medicine: true,
      Customer: true
    }
  });
  return result;
};
var getOrderById = async (CustomerId, id) => {
  const result = await prisma.orders.findMany({
    where: {
      id,
      Customer_id: CustomerId
    },
    include: {
      Medicine: true
    }
  });
  return result;
};
var UpdateOrders = async (SellerId, status, id) => {
  const result = await prisma.orders.update({
    where: {
      id,
      Seller_id: SellerId
    },
    data: {
      status
    }
  });
  return result;
};
var getAllOrders = async () => {
  const result = await prisma.orders.findMany({
    include: {
      Customer: true,
      Seller: true,
      Medicine: true
    }
  });
  return result;
};
var orderServices = {
  createOrder,
  getCustomerOrders,
  getOrderById,
  getSelleOrders,
  UpdateOrders,
  getAllOrders
};

// src/models/orders/orders.controller.ts
var createOrders = async (req, res) => {
  try {
    const customerId = req.user?.id;
    const result = await orderServices.createOrder(req.body, customerId);
    res.status(201).json({
      success: true,
      data: result,
      message: "Order created Successfully"
    });
  } catch (err) {
    res.status(500).json({
      message: "Error creating order",
      success: false
    });
  }
};
var getCustomerOrders2 = async (req, res) => {
  try {
    const session = await auth.api.getSession({
      headers: req.headers
    });
    if (!session) {
      return res.status(401).json({
        message: "Unauthorized",
        success: false
      });
    }
    if (!session || session.user.role !== "CUSTOMER" /* CUSTOMER */) {
      return res.status(401).json({
        message: "Unauthorized",
        success: false
      });
    }
    const CustomerId = session.user.id;
    const result = await orderServices.getCustomerOrders(CustomerId);
    res.status(201).json({
      success: true,
      data: result,
      message: "Order get Successfully"
    });
  } catch (err) {
    res.status(500).json({
      message: "Failed to get the order",
      success: false
    });
  }
};
var getSellerOrders = async (req, res) => {
  try {
    const session = await auth.api.getSession({
      headers: req.headers
    });
    if (!session || session.user.role !== "SELLER" /* SELLER */) {
      return res.status(401).json({
        message: "Unauthorized",
        success: false
      });
    }
    const sellerId = session.user.id;
    const result = await orderServices.getSelleOrders(sellerId);
    res.status(201).json({
      success: true,
      data: result,
      message: "Order get Successfully"
    });
  } catch (err) {
    res.status(500).json({
      message: "Failed to get the order",
      success: false
    });
  }
};
var getOrdersById = async (req, res) => {
  try {
    const session = await auth.api.getSession({
      headers: req.headers
    });
    if (!session || session.user.role !== "CUSTOMER" /* CUSTOMER */) {
      return res.status(401).json({
        message: "Unauthorized",
        success: false
      });
    }
    const { id } = req.params;
    const CustomerId = session.user.id;
    const result = await orderServices.getOrderById(CustomerId, id);
    res.status(201).json({
      success: true,
      data: result,
      message: "Order get Successfully"
    });
  } catch (err) {
    res.status(500).json({
      message: "Failed to get the order",
      success: false
    });
  }
};
var updateOrders = async (req, res) => {
  try {
    const session = await auth.api.getSession({
      headers: req.headers
    });
    if (!session || session.user.role !== "SELLER" /* SELLER */) {
      return res.status(401).json({
        message: "Unauthorized",
        success: false
      });
    }
    const { id } = req.params;
    const { status } = req.body;
    const SellerId = session.user.id;
    const result = await orderServices.UpdateOrders(SellerId, status, id);
    res.status(200).json({
      message: "Order updated successfully",
      success: true,
      data: result
    });
  } catch (err) {
    res.status(500).json({
      message: "Order update failed",
      success: false,
      error: err.message
    });
  }
};
var getAllOrders2 = async (req, res) => {
  try {
    const result = await orderServices.getAllOrders();
    res.status(200).json({
      message: "Order get successfully",
      success: true,
      data: result
    });
  } catch (err) {
    res.status(500).json({
      message: "Order get failed",
      success: false,
      error: err.message
    });
  }
};
var orderController = {
  createOrders,
  getSellerOrders,
  getOrdersById,
  getCustomerOrders: getCustomerOrders2,
  updateOrders,
  getAllOrders: getAllOrders2
};

// src/models/orders/orders.routes.ts
var router3 = Router3();
router3.post("/", auth_middleware_default("CUSTOMER" /* CUSTOMER */), orderController.createOrders);
router3.get("/customer", auth_middleware_default("CUSTOMER" /* CUSTOMER */), orderController.getCustomerOrders);
router3.get("/seller", auth_middleware_default("SELLER" /* SELLER */), orderController.getSellerOrders);
router3.get("/admin", auth_middleware_default("ADMIN" /* ADMIN */), orderController.getAllOrders);
router3.patch("/:id", auth_middleware_default("SELLER" /* SELLER */), orderController.updateOrders);
router3.get("/:id", orderController.getOrdersById);
var OrderRoutes = router3;

// src/models/reviews/reviews.routes.ts
import { Router as Router4 } from "express";

// src/models/reviews/reviews.services.ts
var createReview = async (reviewData, CustomerId) => {
  const result = await prisma.reviews.create({
    data: {
      ...reviewData,
      customer_id: CustomerId
    }
  });
  return result;
};
var getReviews = async (medicineId) => {
  const result = await prisma.reviews.findMany({
    where: {
      medicine_id: medicineId
    },
    include: {
      Customer: {
        select: {
          name: true,
          email: true,
          image: true
        }
      }
    },
    orderBy: {
      createdAt: "desc"
    }
  });
  return result;
};
var ReviewsServices = {
  createReview,
  getReviews
};

// src/models/reviews/reviews.controller.ts
var createReview2 = async (req, res) => {
  try {
    const CustomerId = req.user?.id;
    const result = await ReviewsServices.createReview(req.body, CustomerId);
    res.status(200).json({
      message: "Review inserted successfully",
      success: true,
      data: result
    });
  } catch (err) {
    res.status(500).json({
      message: "Review insertion failed",
      success: false,
      error: err.message
    });
  }
};
var getReviews2 = async (req, res) => {
  try {
    const { medicineId } = req.params;
    const result = await ReviewsServices.getReviews(medicineId);
    res.status(200).json({
      message: "Review fetched successfully",
      success: true,
      data: result
    });
  } catch (err) {
    res.status(500).json({
      message: "Review fetch failed",
      success: false,
      error: err.message
    });
  }
};
var ReviewsController = {
  createReview: createReview2,
  getReviews: getReviews2
};

// src/models/reviews/reviews.routes.ts
var router4 = Router4();
router4.post("/", auth_middleware_default("CUSTOMER" /* CUSTOMER */), ReviewsController.createReview);
router4.get("/:id", ReviewsController.getReviews);
var ReviewsRouter = router4;

// src/models/user/user.routes.ts
import { Router as Router5 } from "express";

// src/models/user/user.services.ts
var updateUser = async (id, role, status) => {
  const result = await prisma.user.update({
    where: {
      id
    },
    data: {
      role,
      status
    }
  });
  return result;
};
var getAllUser = async () => {
  const result = await prisma.user.findMany({
    where: {
      OR: [
        { role: "SELLER" },
        { role: "CUSTOMER" }
      ]
    }
  });
  return result;
};
var UserServices = {
  updateUser,
  getAllUser
};

// src/models/user/user.controller.ts
var updateUser2 = async (req, res) => {
  try {
    const { role, status } = req.body;
    const { id } = req.params;
    const result = await UserServices.updateUser(id, role, status);
    res.status(200).json({
      message: "User updated successfully",
      success: true,
      data: result
    });
  } catch (err) {
    res.status(500).json({
      message: "User update failed",
      success: false,
      error: err.message
    });
  }
};
var getAllUser2 = async (req, res) => {
  try {
    const result = await UserServices.getAllUser();
    res.status(200).json({
      message: "All users fetched successfully",
      success: true,
      data: result
    });
  } catch (err) {
    res.status(500).json({
      message: "cant get all users",
      success: false,
      error: err.message
    });
  }
};
var UserController = {
  updateUser: updateUser2,
  getAllUser: getAllUser2
};

// src/models/user/user.routes.ts
var router5 = Router5();
router5.patch("/:id", auth_middleware_default("ADMIN" /* ADMIN */), UserController.updateUser);
router5.get("/", auth_middleware_default("ADMIN" /* ADMIN */), UserController.getAllUser);
var UserRouter = router5;

// src/models/cart/cart.routes.ts
import { Router as Router6 } from "express";

// src/models/cart/cart.services.ts
var addTocart = async (cartData, CustomerId) => {
  const result = await prisma.cart.create({
    data: {
      ...cartData,
      Customer_id: CustomerId
    }
  });
  return result;
};
var getAllCart = async (CustomerId) => {
  const result = await prisma.cart.findMany({
    where: {
      Customer_id: CustomerId
    },
    include: {
      Medicine: true
    }
  });
  return result;
};
var deleteCart = async (id) => {
  const result = await prisma.cart.delete({
    where: {
      id
    }
  });
  return result;
};
var cartServices = {
  addTocart,
  deleteCart,
  getAllCart
};

// src/models/cart/cart.controler.ts
var addtoCart = async (req, res) => {
  try {
    const CustomerId = req.user?.id;
    const result = await cartServices.addTocart(req.body, CustomerId);
    res.status(200).json({
      message: "Product added to cart successfully",
      success: true,
      data: result
    });
  } catch (err) {
    res.status(500).json({
      message: err.message,
      success: false
    });
  }
};
var deleteCart2 = async (req, res) => {
  try {
    const { id } = req.params;
    const result = await cartServices.deleteCart(id);
    res.status(200).json({
      message: "Product deleted from cart successfully",
      success: true,
      data: result
    });
  } catch (err) {
    res.status(500).json({
      message: err.message,
      success: false
    });
  }
};
var getALlCart = async (req, res) => {
  try {
    const CustomerId = req.user?.id;
    const result = await cartServices.getAllCart(CustomerId);
    res.status(200).json({
      message: "All cart fetched successfully",
      success: true,
      data: result
    });
  } catch (err) {
    console.log("Add to cart error", err);
    res.status(500).json({
      message: err.message,
      success: false
    });
  }
};
var cartController = {
  addtoCart,
  deleteCart: deleteCart2,
  getALlCart
};

// src/models/cart/cart.routes.ts
var router6 = Router6();
router6.post("/", auth_middleware_default("CUSTOMER" /* CUSTOMER */), cartController.addtoCart);
router6.get("/", auth_middleware_default("CUSTOMER" /* CUSTOMER */), cartController.getALlCart);
router6.delete("/:id", auth_middleware_default("CUSTOMER" /* CUSTOMER */), cartController.deleteCart);
var cartRouter = router6;

// src/app.ts
var app = express();
app.use(cors({
  origin: process.env.APP_URL,
  credentials: true
}));
app.use(express.json());
app.all("/api/auth/*splat", toNodeHandler(auth));
app.use("/api/medicine", medicineRouter);
app.use("/api/categories", CategoriesRouter);
app.use("/api/orders", OrderRoutes);
app.use("/api/reviews", ReviewsRouter);
app.use("/api/user", UserRouter);
app.use("/api/cart", cartRouter);
app.get("/", (req, res) => {
  res.send("Hello World");
});
var app_default = app;

// src/index.ts
var index_default = app_default;
export {
  index_default as default
};
